#+TITLE: Μοντελοποιήση της βιομάζας του C. Glycerinogenes στο Aspen

Για την ολοκληρωμένη προσωμοίωση της βιοαντίδρασης, απαιτείται μοντελοποίηση της βιομάζας του μικροοργανισμού C. glycerinogenes στο Aspen. Αυτό είναι δύσκολο διότι δεν υπάρχουν πολλές πληροφορίες για αυτό. Όμως, σύμφωνα με τους [[cite:&wooleyDevelopmentASPENPhysical1996]] ο μοριακός τύπος της βιομάζας (ο οποίος μπορεί να προκύψει μέσω της στοιχειομετρίας της) αρκεί για όλα τα δεδομένα που θεωρεί απαραίτητα το Aspen. Η βιομάζα μπορεί να οριστεί ως ένα conventional solid στο Aspen. Για αυτό, τα δεδομένα που χρειάζεται το Aspen είναι τα εξής: Μοριακό βάρος, θερμότητα σύνθεσης, θερμοχωρητικότητα και πυκνότητα.

Ο μοριακός τύπος υπολογίζεται με τη βοήθεια του αρχείου biomass_properties ο οποίος χρησιμοποιεί τους υπολογισμούς της στοιχειομετρίας για να προσδιορίσει τον τύπο της βιομάζας. Ο τύπος που προκύπτει είναι ο \( C_{3.33}H_{4.72}O_{3.38}N_{0.05}P_{0.0015} \) . Το μοριακό βάρος υπολογίζεται απευθείας από τα ατομικά βάρη C, H, O, N, P ως MW = 99.592 g/mol. Η πυκνότητα του υλικού μπορεί να υποτεθεί παρόμοια του αμύλου (περίπου 1.5 g/ml). Για την θερμοχωρητικότητα του υλικού, μπορεί να χρησιμοποιηθεί [[https://en.wikipedia.org/wiki/Kopp%27s_law][ο κανόνας του Kopp]] ο οποίος λέει ότι η θερμοχωρητικότητα ενός υλικού μπορεί να προσδιοριστεί από τα στοιχεία του ως \[ C = \sum_{i=1}^{N} C_{i}f_i \] σε \( \left[ \frac{J}{kg \cdot K} \right] \) όπου C_i η θερμοχωρητικότητα του κάθε στοιχείου στις μονάδες αυτές και f_i το κλάσμα μάζας του στοιχείου. Ο νόμος αυτός δουλεύει καλά σε χαμηλές θερμοκρασίες, στις οποίες γίνεται και η βιοαντίδραση. Για την παραπάνω βιομάζα προκύπτει ίσο με 2664 J/kg K.

Τέλος, για την θερμότητα σύνθεσης, μπορεί να υπολογιστεί εύκολα η θερμότητα καύσης της ένωσης και από αυτήν η θερμότητα σύνθεσης. Καθώς αυτό αφορά μία τελείως άλλη αντίδραση, οι υπολογισμοί του είναι σε ξεχωριστό αρχείο biomass_combustion.
Προκύπτει η αντίδραση
\[  C_{3.33}H_{4.72}O_{3.38}N_{0.05}P_{0.0015} + 5.65 O_2 \rightarrow 2.36H_2O + 3.33CO_2+7.5 \cdot 10^{-4} P_2O_5 + 2.52 \cdot 10^{-2} N_2 \]
Η επίδραση του πεντοξειδίου του φωσφόρου στην θερμότητα καύσης μπορεί να θεωρηθεί αμελητέα καθώς είναι αρκετές τάξες μεγέθους μικρότερη ποσότητα από αυτές του νερού και του διοξειδίου του άνθρακα ενώ το άζωτο θεωρείται αδρανές. Άρα, η θερμότητα καύσης προκύπτει από τις θερμότητες σύνθεσης H_2O και CO_2 οι οποίες είναι \( -68.7979 \frac{kcal}{mol} \) και \( -94.052 \frac{kcal}{mol} \) αντίστοιχα. Άρα, η θερμότητα σύνθεσης της βιομάζας είναι 475.92 kcal/mol.

Στον παρακάτω πίνακα συνοψίζονται οι απαραίτητες ιδιότητες για να μοντελοποιηθεί η βιομάζα στο Aspen.
#+CAPTION: Απαραίτητες ιδιότητες βιομάζας
| Ιδιότητα           | Τιμή              |
|--------------------+-------------------|
| Μοριακό Βάρος      | 99.592 (g/mol)    |
| Πυκνότητα          | 1.5 (g/ml)        |
| Θερμοχωρητικότητα  | 2664 (J/kg K)     |
| Θερμότητα σύνθεσης | 475.92 (kcal/mol) |
