#+TITLE: Στοιχειομετρία Βιοαντιδραστήρα

Η βιοαντίδραση που θα χρησιμοποιηθεί είναι μία περίπλοκη αντίδραση της οποίας η στοιχειομετρία μπορεί πολύ δύσκολα να προσδιοριστεί ακριβώς. Επειδή απαιτείται μία έκφραση χημικής αντίδρασης για να μπεί στο ασπεν, θα γίνει μία προσέγγιση της παραγωγής προιόντων με βάση τις ποσότητες που παράγονται. Η αντίδραση που θα υποτεθεί είναι η
\[ S + U + C \rightarrow G + Ar + E + Ac\]
όπου S = γλυκόζη (substrate), U = ουρία, C = CSL, G = γλυκερόλη, Ar = αραβιτόλη, Ε = αιθανόλη, Ac = οξικό οξύ
δηλαδή πως η γλυκόζη "διασπάται" σε γλυκερόλη, αιθανόλη, οξικό οξύ και αραβιτόλη.

Στην πράξη η αντίδραση αυτή είναι αερόβια (πρέπει να υπάρχει οξυγόνο στα αντιδρώντα), αφορά την ανάπτυξη ενός μικροοργανισμού (πρέπει να υπάρχει βιομάζα στα προιόντα) και θα έχει και νερό και CO_2 ως προιόντα όπως όλες οι μικροβιακές αντιδράσεις. Λόγω έλλειψης δεδομένων, στο ασπεν, η αντίδραση θα μοντελοποιηθεί με βάση το παραπάνω.

Στην αντίδραση συμμετέχουν 32692.2 tn γλυκόζη, 283.74 tn ουρία και 567.57 tn CSL. Όμως, βάση προηγούμενων παραδοχών, έχουμε πει πως δεν αντιδρά όλη η ουρία και όλο το CSL. Έχουμε υποθέσει ότι αντιδρούν τα 3/4 της ουρίας και το μισό CSL. Άρα, 212.8 tn ουρία και 283.79 tn CSL. Τα προιόντα είναι 13643 tn γλυκερόλη, 640.68 tn αραβιτόλη, 168.82 tn αιθανόλη και 165.99 tn οξικό οξύ. Αρχικά, πρέπει να μετατρεπούν οι ποσότητες αυτές σε mol και έπειτα, από τις αναλογίες τους να βρεθούν οι συντελεστές. Ως βάση των υπολογισμών θα χρησιμοποιηθεί το 1 mol γλυκερόλης.

Οι σχετικοί υπολογισμοί φαίνονται στο ομώνυμο αρχείο matlab στον φάκελο /Calculations.

Η στοιχειομετρία της αντίδρασης που προκύπτει είναι
\[ 1.22S + 0.024U + 0.049C \rightarrow G + 0.028Ar + 0.025E + 0.019Ac \]
Αξίζει να αναφερθεί πως το CSL ορίστηκε ως ένα συστατικό με την σύσταση που φαίνεται στον παρακάτω πίνακα από την οποία προκύπτει ο εμπειρικός τύπος
\( C_{0.94}H_{2.94}O_{1.41}N_{0.04}P_{0.03}K_{0.03} \)
#+CAPTION: Σύσταση του CSL στα συστατικά του
| Συστατικό             | Περιεκτικότητα |
|-----------------------+----------------|
| Νερό                  |            0.6 |
| Γαλακτικό Οξύ         |           0.15 |
| Ζάχαρες σε ισοδύναμη  |           0.05 |
| συγκέντρωση γλυκόζης  |                |
| Τέφρα                 |            0.1 |
| Αμινοξέα σε ισοδύναμη |           0.03 |
| συγκέντρωση αλανίνης  |                |
| Αμμωνία               |           0.01 |
| Φώσφορος              |           0.03 |
| Κάλιο                 |           0.03 |
|-----------------------+----------------|
| Άθροισμα              |              1 |

Αξίζει να αναφερθεί πως στον πίνακα αυτό έχουν υπερεκτιμηθεί ορισμένα από τα συστατικά σε σχέση με τις τιμές τους στην αντίστοιχη βιβλιογραφία (δες [[id:d01ccf54-e2ce-4a6b-b826-652acf6a4c65][Corn Steep Liquor (CSL) - Ένα Χρήσιμο Θρεπτικό Συστατικό σε Μικροβιακές Καλλιέργειες]]). Αυτό συμβαίνει επειδή με βάση τις τιμές εκείνες ήταν αδύνατον να αθροιστούν τα συστατικά στη μονάδα.

Υπενθυμίζεται πως έχει προσδιοριστεί μία τεχνική κινητική παραγωγής γλυκερόλης συναρτήσει της γλυκόζης ίση με \[ r_G = 0.257 [S]^{0.335} \], η οποία με βάση αυτή τη στοιχειομετρία είναι και ο συνολικός ρυθμός της αντίδρασης (καθώς ο συντελεστής της γλυκερόλης είναι μονάδα). Στην πραγματικότητα, ο ρυθμός ανάπτυξης εξαρτάται από την συγκέντρωση υποστρώματος και βιομάζας με βάση το μοντέλο Monod και υπάρχει πιθανότητα να παίζουν ρόλο και οι συγκεντρώσεις των άλλων θρεπτικών συστατικών. Όμως, καθώς έχει γίνει η παραδοχή πως η γλυκόζη είναι το σημαντικό (και το περιοριστικό) υπόστρωμα, η διαστασιολόγηση του αντιδραστήρα θα γίνει με βάση τον ρυθμό αυτόν.
 
Εφόσον στην αντίδραση αυτή δεν έχουν συμπεριληφθεί O_2 στα αντιδρώντα και βιομάζα, H_2O και CO_2 στα προιόντα, δεν θα κλείνουν τα στοιχειακά ισοζύγια για την αντίδραση. Απουσία άλλων δεδομένων, οι συντελεστές Ο_2, CO_2, H_2O και βιομάζας θα ληφθούν όλοι ίσοι με την μονάδα και ο τύπος της βιομάζας θα προκύψει έτσι ώστε να κλείνει το ισοζύγιο. Αν συμπεριληφθούν O_2 στα αντιδρώντα και CO_2, H_2O στα προιόντα όλα με συντελεστή μονάδα, τότε προκύπτει πως η βιομάζα θα έχει τύπο \( C_{3.167}H_{4.333}O_{3.217}N_{0.05} \). Άρα, η συνολική μικροβιακή αντίδραση που διεξάγεται θα είναι η
\[ 1.22S + 0.24U + 0.049C + O_2 \rightarrow C_{3.167}H_{4.333}O_{3.217}N_{0.05} + G + 0.028Ar +0.025E + 0.019Ac + H_2O +CO_2 \]

