#+TITLE: Οικονομικό Δυναμικό Παραγωγής Γλυκερόλης

Θέλουμε να υπολογίσουμε το οικονομικό δυναμικό της παραγωγής γλυκερόλης από τον C. glycerinogenes με βάση τους [[cite:&jinByproductFormationNovel2003;&zhugeGlycerolProductionNovel2001]] .

Με βάση τους [[cite:&jinByproductFormationNovel2003]] απαιτούνται 230.44 g/l γλυκόζη, 2 g/l ουρία και 4 g/l Corn Steep Liquor. Ως προιόν θεωρούμε το 96.17 g/l γλυκερόλη. Επίσης, η γλυκόζη είναι από απόβλητα και δεν κοστολογείται. Αξίζει επίσης να αναφερθεί πως η αντίδραση αυτή έχει ως παραπροιόντα την αραβιτόλη, την αιθανόλη και το οξικό οξύ. Με βάση τους [[cite:&zhugeGlycerolProductionNovel2001]], η αντίδραση αυτή παράγει 4.516 g/l αραβιτόλη, 1.19 g/l αιθανόλη και 1.17 g/l οξικό οξύ. Δεν χρησιμοποιήθηκαν δεδομένα από το ίδιο πείραμα για αυτά καθώς η δομή των δεδομένων για την εφαρμογή της στην κινητική από το διάγραμμα στο [[cite:&jinByproductFormationNovel2003]] ήταν πιό βολική, ενώ το προφιλ παραγωγής παραπροιόντων ήταν πιό καλά παρουσιασμένο στο [[cite:&zhugeGlycerolProductionNovel2001]].

Αξίζει να σημειωθεί πως 4 g CSL αντιστοιχούν σε 35.71 mg P, ενώ σύμφωνα με τις βέλτιστες συνθήκες που προσδιόρισαν οι [[cite:&zhugeGlycerolProductionNovel2001]] θέλουμε 55-65 mg P/l. Η πειραματική διαδικασία προέκυψε από την μελέτη [[cite:&jinByproductFormationNovel2003]] και όχι την μελέτη των βέλτιστων συνθηκών επειδή στο άρθρο αυτό αναφερόταν και η συγκέντρωση της βιομάζας η οποία είναι απαραίτητη για μία σωστή κινητική μελέτη.

Για αντιδραστήρα 2985.9 m^3, θέλουμε 75000 τόνους γλυκόζη, 650.93 τόνους ουρία και 1301.9 τόνους Corn steep liquor. Η παραγωγικότητα είναι 31298 τόνοι γλυκερόλη. Τα παραπροιόντα είναι 1469.8 τόνοι αραβιτόλη, 387.30 τόνοι αιθανόλη και 380.79 τόνοι οξικό οξύ το χρόνο. Παρότι τα παραπροιόντα αυτά είναι σε μικρές συγκεντρώσεις, μέσα στα 109 batches που γίνονται το χρόνο και στο working volume των 2985.9 m^3 που χρησιμοποιούμε, οι συνολικές ποσότητες είναι σημαντικές. Άρα, αξίζει να μελετηθεί τι θα γίνουν τα παραπροιόντα αυτά.

Η γλυκερόλη έχει τιμή 721.07 ευρώ ανά τόνο, η ουρία 638.13 ευρώ ανά τόνο ενώ το corn steep liquor 360 ευρώ ανά τόνο. https://www.echemi.com/productsInformation/pid_Seven41077-glycerol.html
https://www.indiamart.com/proddetail/corn-steep-liquor-15744963191.html
https://tradingeconomics.com/commodity/urea

Ανάγοντας τα στα παραπάνω μεγέθη, το κόστος των πρώτων υλών είναι 415.38 χιλιάδες ευρώ για την ουρία και 468.67 χιλιάδες για το CSL (συνολικό κόστος 884.05 χιλιάδες ευρώ) ενώ το κέρδος είναι 22.57 εκατομμύρια. Άρα, το οικονομικό δυναμικό της διεργασίας είναι 21.68 εκατομμύρια.

Βέβαια, ο όγκος του αντιδραστήρα που χρησιμοποιήθηκε είναι επικίνδυνα μεγάλος άρα πρέπει να δούμε αν θα δημιουργήσει αυτό προβλήματα.
