#+TITLE: Ισοζύγια Μάζας και Υπολογισμοί για την Παραγωγή Γλυκερόλης

* Ισοζύγια μάζας στην τροφοδοσία
Η αρχική τροφοδοσία είναι 200.000 tn πυρηνόξυλο. Η σύσταση αυτού σε κυτταρίνη, ημικυτταρίνη, λιγνίνη και άλλα συστατικά θα προκύψει ως μέσος όρος των αποτελεσμάτων των [[cite:&koutsomitopoulouPreparationCharacterizationOlive2014;&fernandez-bolanosCharacterizationLigninObtained1999;&gonzalezCombustionOptimisationBiomass2004a]]

Με βάση αυτά, το 37% είναι κυτταρίνη, το 26.5% ημικυτταρίνη, 23.75% λιγνίνη, 8.93% υγρασία, 2.3% τέφρα. Αυτά αθροίζονται στο 98.35% της συνολικής βιομάζας. Τα trace elements (N, Cl, Fe, Al και άλλα μέταλλα) συνυπολογίζονται στο 0.92% της βιομάζας άρα στο σύνολο έχουμε το 99.3% της βιομάζας. Το υπόλοιπο είναι λόγω σφαλμάτων στρογγυλοποίησης καθώς χρησιμοποιήθηκαν δεδομένα από 3 διαφορετικές πηγές. Μπορούν να αποδοθούν σε κάποιο απο τα βασικά συστατικά του ρεύματος. Για να βγαίνουν σχεδόν 100%, μπορούμε να στρογγυλοποίησουμε την υγρασία στο 9% και να πούμε ότι η λιγνίνη είναι 24.2%, το οποίο δίνει σύνολο 99.9%. Αν θέλουμε να υπολογιστεί το 100%, μπορούμε να πούμε και ότι τα trace elements είναι 1% αντί για 0.92% (υποθέτοντας ότι το υπόλοιπο 0.08% δεν έχει εντοπιστεί).

* Προκατεργασία βιομάζας με steam explosion - Yields των συστατικών
Έπειτα, μελετάμε το yield της εκρήξης ατμού με βάση τα δεδομένα των [[cite:&fernandez-bolanosSteamexplosionOliveStones2001]] . Βλέπουμε πως πιό αποδοτική είναι η διεργασία για Τ = 232 C και χρόνο παραμονής 2 λεπτά, με Ro = 4.22. Σε αυτήν, η υδατοδιαλυτή φάση είναι το 25.5% του συνολικού ενώ στην στερεή φάση ανακτάται το 52.9% της βιομάζας εκ του οποίου το 37.7% είναι στο κλάσμα της κυτταρίνης και το 15.2% της λιγνίνης.

Στην υγρή φάση είναι η ημικυτταρίνη και φαινόλες. Αφαιρόντας την σύσταση των φαινολών (2.5%) βρίσκουμε πως ανακτήθηκε το 93.8% της συνολικής ημικυτταρίνης. Το υπόλοιπο ή διασπάστηκε θερμικά κατά την διεργασία ή δεν διαλύθηκε. Ακόμη, από την σύσταση της φάσης αυτής, ξέρουμε ότι το 51.4% είναι ζάχαρες, δηλαδή έχουμε ως προιόν 26214 tn ημικυτταρινικές ζάχαρες. Οι φαινόλες θεωρούμε πως ανακτόνται πλήρως μέσω εκχύλισης, ενώ τα υπόλοιπα πηγαίνουν στον αντιδραστήρα παραγωγής φουρφουράλης όπου δραστική είναι μόνο η ξυλόζη ενώ τα υπόλοιπα συστατικά θα υποθέσουμε ότι είναι αδρανή. Η ξυλόζη είναι το 45.7% της υδατοδιαλυτής φάσης, άρα η τροφοδοσία της θα είναι 23307 tn/y.

Από τη στερεή φάση, βλέπουμε πόση λιγνίνη ανακτάται το οποίο είναι το 62.8% της συνολικής. Στην κυτταρινική φάση υπάρχει περίσεμα ποσότητας καθώς βγαίνει μεγαλύτερη από την κυτταρίνη που υπάρχει στο δείγμα. Τα υπόλοιπα είναι λιγνίνη που δεν αφαιρέθηκε και αδιάλυτη ημικυτταρίνη.

Για να δούμε πόση κυτταρίνη έχει πραγματικά το κλάσμα αυτό, πρέπει να σκεφτούμε τι διασπάστηκε. Για αυτό, δεν υπάρχουν λεπτομερή δεδομένα και απαιτείται να γίνουν κάποιες παραδοχές, αλλά ξέρουμε πως η ημικυτταρίνη είναι η πιό επιρρεπής στην θερμική διάσπαση και άρα μπορούμε να υποθέσουμε πως ότι δεν διαλύθηκε διασπάστηκε θερμικά ενώ η λιγνίνη είναι η πιό θερμοάντοχη. Άρα, πέρα από την ημικυτταρίνη, ένα σημαντικό ποσοστό της θερμικά αποδομημένης βιομάζας θα είναι κυτταρίνη. Επίσης, πέρα από τις φαινόλες της λιγνίνης, μπορούμε να υποθέσουμε πως δεν διαλύθηκε άλλη ποσότητα κυτταρίνης ή λιγνίνης στο νερό άρα ότι απώλεια έχουμε είναι θερμική. Η απώλεια λιγνίνης είναι 37.2%. Θα υποθέσουμε ότι μόνο ένα 10% αυτού είναι θερμική διάσπαση καθώς η θερμοκρασία είναι σχετικά χαμηλή για την λιγνίνη. Άρα διασπάστηκε ένα 3.72% της συνολικής λιγνίνης.

Υπό αυτές τις παραδοχές, βρίσκουμε ότι το κυτταρινικό κλάσμα έχει 60486 tn κυτταρίνη και 14914 tn λιγνίνη. Άρα, ανακτάται το 81.74% της συνολικής κυτταρίνης, και το κλάσμα αυτό είναι κατά 19.78% λιγνίνη. Έπειτα, το κλάσμα αυτό ακολουθεί κατεργασία με ClO_2 το οποίο σε όξινες συνθήκες οξειδώνει την λιγνίνη και δημιουργεί ίζημα το οποίο διαχωρίζεται με διήθηση. Το ρεύμα της καθαρής πλέον κυτταρίνης (60486 tn/y) υδρολύεται 

Έπειτα, η κυτταρίνη αυτή υδρολύεται παράγοντας γλυκόζη με την μέγιστη δυνατή απόδοση (εφόσον έχει απολιγνοποιηθεί). Αυτό είναι 30.9% της μάζας του ξηρού υποστρώματος της έκρηξης ατμού, δηλαδή των 105800 tn/y. Άρα, παράγονται 32692.2 tn/y γλυκόζη. Αυτή είναι η γλυκόζη που μπαίνει στον βιοαντιδραστήρα ως υπόστρωμα.

* Ισοζύγιο μάζας βιοαντιδραστήρα
Για τον βιοαντιδραστήρα, τα ισοζύγια που αφορούν τι ποσότητες μπαίνουν και τι βγαίνουν έχουν γίνει με βάση βιβλιογραφικά δεδομένα κινητικών πειραμάτων. Ένας υπολογισμός ο οποίος όμως δεν έχει γίνει και είμαστε σε θέση να κάνουμε είναι η ποσότητα λιγνίνης που απαιτείται για την απομάκρυνση των αζωτούχων ουσιών. Επίσης, πρέπει να γίνουν οι υπολογισμοί των αποστακτικών στηλών για να δούμε πόση καθαρή γλυκερόλη ανακτάται, αλλά αυτό θα απαιτήσει υπολογισμούς στο Aspen.

Σύμφωνα με τους [[cite:&wallersteinMethodRecoveringGlycerol1946]], η λιγνίνη που απαιτείται είναι κατά μάζα ίση με τα αζωτούχα συστατικά στον αντιδραστήρα. Μην έχοντας κινητικά δεδομένα για την κατανάλωση της ουρίας και του CSL στον αντιδραστήρα, ή την στοιχειομετρία της αντίδρασης που συμβαίνει σε αυτόν, είναι δύσκολο να προβλέψουμε την ποσότητα αζώτου στην έξοδο. Μπορεί να υπολογιστεί αυτή στην είσοδο και να υποθέσουμε μία μετατροπή που θα έχει στον αντιδραστήρα.

Η ουρία έχει χημικό τύπο \( CO(NH_2)_2 \). Με βάση το μοριακό βάρος της και το ατομικό βάρος του αζώτου, βρίσκουμε ότι το 46.667% της ουρίας είναι άζωτο κατά μάζα. Για την κατανάλωση της, ξέρουμε από τους [[cite:&zhugeGlycerolProductionNovel2001]] ότι αν βάλουμε στον αντιδραστήρα 1g/l ουρία, στο τέλος της αντίδρασης θα περίσσεψει πολύ περισσότερη γλυκόζη από ότι αν βάλουμε 2g/l. Αυτό σημαίνει ότι στο 1g/l η ουρία θα ήταν το περιοριστικό υπόστρωμα. Επίσης όμως, αν αυξήσουμε την ποσότητα πάνω από 2 g/l, η απόκριση της αντίδρασης είναι αμελητέα. Άρα στο 2 g/l δεν είναι περιοριστικό υπόστρωμα η ουρία. Απουσία άλλων δεδομένων, θα υποθέσουμε ότι η κατανάλωση είναι μεταξύ του 1 και του 2, άρα έστω περίπου 1.5 g/l. Δηλαδή στο τέλος της αντίδρασης υπάρχουν 0.5 g/l ουρία άρα 0.233 g/l άζωτο.

Για το CSL, σύμφωνα με τους [[cite:&zhugeGlycerolProductionNovel2001]], η παρουσία του παίζει καθοριστικό ρόλο στην ανάπτυξη του μικροοργανισμού, καθώς προσφέρει πολλά θρεπτικά συστατικά. Βέβαια, δεν αποτελεί περιοριστικό υπόστρωμα και η προσθήκη μεγαλύτερης ποσότητας αυξάνει τον ρυθμό λόγω παρουσίας περισσότερων απαραίτητων θρεπτικών συστατικών. Απουσία άλλων πληροφοριών, θα υποτεθεί ότι καταναλώνεται το 50% στην αντίδραση για να γίνουν οι παρακάτω υπολογισμοί. To CSL που έχουμε χρησιμοποιήσει για την κοστολόγηση ([[https://www.indiamart.com/proddetail/corn-steep-liquor-15744963191.html][Indiamart]]) έχει 3.94% άζωτο. Άρα, θα υπάρχουν 0.0788 g/l άζωτο από το CSL.

Στο σύνολο, στην έξοδο του αντιδραστήρα με βάση αυτές τις παραδοχές θα υπάρχει περίπου 0.3121 g/l άζωτο.

Με βάση τους υπολογισμούς της κινητικής που έχουν γίνει, ο όγκος του αντιδραστήρα θα είναι 1301.5 m^3, άρα το συνολικό άζωτο που θα υπάρχει στην έξοδο του αντιδραστήρα άνα batch θα είναι 406.21 kg άζωτο. Κάθε χρόνο γίνονται 109 batches με βάση τον χρόνο παραμονής που έχει επιλεχθεί, άρα ετησίως ο αντιδραστήρας έχει στην έξοδο του 44.28 tn άζωτο. Στην πράξη, μπορεί να υπάρχει και ένα μέρος του αρχικού αζώτου το οποίο υπήρχε στο πυρηνόξυλο στον αντιδραστήρα. Θα υποθέσουμε απουσία άλλων δεδομένων πως το άζωτο στο κυτταρινικό κλάσμα είναι το 0.4% της συνολικής τροφοδοσίας. Πιθανόν να έχει μείνει και λιγότερο από αυτό, αλλά σύμφωνα με τους [[cite:&wallersteinMethodRecoveringGlycerol1946]], μία μικρή περίσσεια λιγνίνης δεν δημιουργέι πρόβλημα.

Άρα, πρέπει να πάρουμε 286.22 tn λιγνίνη (ή και λίγο παραπάνω) από το ρεύμα της για τον διαχωρισμό του αζώτου στην έξοδο του βιοαντιδραστήρα.

Η υπόλοιπη (30113 tn περίπου) καίγεται για παραγωγή 707.65 TJ/y ενέργειας
