#+TITLE: Προκατεργασία της Βιομάζας και Βιοαντιδραστήρας - 2η πρόοδος Σχεδιασμού Διεργασιών
#+AUTHOR: Βιδιάνος Γιαννίτσης
#+LATEX_HEADER: \usepackage[a4paper, margin=3cm]{geometry}
\renewcommand{\abstractname}{Περίληψη}
\renewcommand{\tablename}{Πίνακας}
\renewcommand{\figurename}{Σχήμα}
\renewcommand\listingscaption{Κώδικας}

* Github
Έχουμε φτιάξει repository στο [[https://github.com/Vidianos-Giannitsis/Process-Design][Github]] στο οποίο υπάρχουν πολλά από τα σχετικά αρχεία της εργασίας μας. Ιδιαίτερα στον φάκελο /Calculations υπάρχουν αρκετά από τα αρχεία που χρησιμοποιήθηκαν για υπολογισμούς της εργασίας αν θέλετε να τα δείτε πιό λεπτομερώς από ότι περιγράφονται εδώ.

\pagebreak
* Μελέτη της πρώτης ύλης - Πυρηνόξυλο
Το πυρηνόξυλο είναι ενα λιγνοκυτταρινικό παραπροιόν της επεξεργασίας της ελιάς. Αποτελεί το ξυλώδες κομμάτι του κουκουτσιού όταν έχουν απομακρυνθεί τα έλαια του (πυρηνέλαιο). Καθώς αποτελεί την πρώτη ύλη που θα χρησιμοποιηθεί στην παρούσα εργασία, είναι σημαντικό να ξέρουμε την σύσταση του.

  Με βάση τους [[cite:&koutsomitopoulouPreparationCharacterizationOlive2014]] το πυρηνόξυλο έχει 37.5 % κυτταρίνη, 26% ημικυτταρίνη, 21.5% λιγνίνη και 8% υγρασία. Στοιχειακά αναφέρουν πως έχει 49% άνθρακα και 31% οξυγόνο. Η στοιχειακή ανάλυση αυτή, εμπλουτίζεται από τους [[cite:&gonzalezCombustionOptimisationBiomass2004]] οι οποίοι αναφέρουν 46.5% C, 6.4 Η, 0.4 Ν, 0.34 Cl και μηδενικό θείο που είναι αυτά που τους αφορούν κατά την μελέτη της καύσης. Από μέταλλα αναφέρει σίδηρο σε 1236 mg/kg και αλουμίνιο στα 463 mg/kg. Επίσης μιλάει για πυκνότητα σκόνης πυρηνόξυλου 1.424 g/cm^3. Επίσης οι [[cite:&gonzalezCombustionOptimisationBiomass2004]] αναφέρουν ότι το fixed carbon είναι 16.2% του υλικού, τα πτητικά συστατικά είναι 72.7%, τέφρα 2.3% και υγρασία 8.8%. Τέλος, λένε πως η θερμογόνος δύναμη του ως καύσιμο είναι 19.4 MJ/kg.

  Οι [[cite:&fernandez-bolanosCharacterizationLigninObtained1999]] μιλάνε για την σύσταση της βιομάζας αυτής. Συγκεκριμένα αναφέρουν μία υγρασία 10%, κυτταρίνη 36.5%, ημικυτταρίνη 27% και λιγνίνη 26%. Τα δεδομένα αυτά είναι αρκετά κοντά με τα προηγούμενα για να θεωρηθούν συμβατά άρα νοείται η χρήση του μέσου όρου τους. Επίσης όμως δίνουν και μία στοιχειακή ανάλυση για το κλάσμα της λιγνίνης που καλό είναι να είναι πλήρως προσδιορισμένο επειδή σε αντίθεση με την κυτταρίνη και την ημικυτταρίνη δεν κυριαρχείται από κάποια ουσία. Έκαναν παραπάνω των ένα πειραμάτων με έκρηξη ατμού η οποία χρησιμοποιεί οξύ και που δεν χρησιμοποιεί, αλλά η γενική εικόνα είναι πως ο άνθρακας είναι στο 59.5%, το υδρογόνο στο 5.5% και το οξυγόνο 35% ως τα κύρια συστατικά της λιγνίνης. Για πιο ακριβής υπολογισμούς μπορεί να χρησιμοποιηθεί ο πίνακας 3 του άρθρου. Επιπλέον, υπολογίζουν πως η απομονωμένη λιγνίνη αυτή έχει σημαντικά καλύτερη θερμογόνο δύναμη από το αρχικό υλικό στα 23.5 MJ/kg το οποίο είναι σημαντική αύξηση και συμπεράνουν πως αξίζει τον κόπο ο διαχωρισμός.

  Οι [[cite:&fernandez-bolanosSteamexplosionOliveStones2001]] αναφέρουν την σύσταση της υδατοδιαλυτής φάσης και πόση ανακτάται. Παρατηρούν πως τα σάκχαρα αποτελούν μόνο το 50% της υδατοδιαλυτής φάσης, η τέφρα το 4% περίπου και οι πολυφαινόλες το 2.5%. Το υπόλοιπο είναι άλλα συστατικά. Βρήκαν επίσης την σύσταση της ημικυτταρίνης η οποία είναι 45-50% ξυλόζη, 2-3% αραβινόζη, 1.5% περίπου γαλακτόζη και γλυκόζη και λίγο κάτω από 1% μανόζη. 
  
  Με βάση αυτά, ορίστηκε η σύσταση της τροφοδοσίας της διεργασίας. Επειδή οι τιμές προέκυψαν ως μέσοι όροι, βλέπουμε πως το άθροισμα τους δεν είναι ακριβώς μονάδα. Για αυτό έγιναν κάποιες στρογγυλοποιήσεις προς τα πάνω για να γίνει αυτό.

  #+CAPTION: Σύσταση της τροφοδοσίας στα επιμέρους συστατικά της
  | Ουσία           | Σύσταση |
  |-----------------+---------|
  | Κυτταρίνη       |    0.37 |
  | Ημικυτταρίνη    |   0.265 |
  | Λιγνίνη         |   0.242 |
  | Υγρασία         |    0.09 |
  | Τέφρα           |   0.023 |
  | Trace Elements  |  0.0092 |
  | (N, Cl, Fe, Al) |         |
  |-----------------+---------|
  | Άθροισμα        |   0.999 |


* Τρόποι παραγωγής γλυκερόλης από βιομάζα
Η γλυκερόλη είναι μία αρκετά ιξώδη αλκοόλη, η οποία έχει πολλές εφαρμογές και ως πρώτη ύλη για την παραγωγή άλλων προιόντων αλλά και αυτή καθ'αυτή. Αποτελεί το βασικό παραπροιόν της βιομηχανίας του βιοντίζελ καθώς στην παραγωγή του γίνεται μία αντίδραση μετεστεροποιήσης σε τριγλυκερίδια η οποία δίνει ως παραπροιόν την γλυκερόλη. Τα τριγλυκερίδια μπορούν να παραχθούν από βιομάζα με τη χρήση ελαιοδών ζυμών άρα, με αυτή τη τεχνική μπορεί να παραχθεί γλυκερόλη από βιομάζα. Βέβαια, καθώς η συνολική παραγωγικότητα της διεργασίας σε γλυκερόλη είναι μόνο το 10% περίπου της συνολικής βιομάζας και η γλυκερόλη που παράγεται απαιτεί καθαρισμό, κρίθηκε πως η διεργασία αυτή δεν είναι κατάλληλη για χρήση.

Ένας άλλος τρόπος για την παραγωγή της γλυκερόλης είναι να συντεθεί προπυλένιο από την βιομάζα το οποίο αποτελεί την τυπική πρώτη ύλη που χρησιμοποιείται για την χημική παραγωγή της γλυκερόλης. Αλλά, και αυτή η διεργασία είναι αρκετά πολύπλοκη και δεν θεωρήθηκε καλή για την εφαρμογή αυτή. Για αυτό, μελετήθηκε η απευθείας βιοχημική μετατροπή της βιομάζας σε γλυκερόλη. Αυτή μπορεί να γίνει για παράδειγμα από τον Saccharomyces cerevisiae υπό ορισμένες συνθήκες, όπως είχε γίνει στον 1ο παγκόσμιο πόλεμο. Βέβαια, η παραγωγικότητα της διεργασίας αυτής είναι αρκετά χαμηλή για αυτό δεν ακολουθήθηκε.

Έτσι, καταλήγουμε στην διεργασία η οποία θα μελετηθεί και παρακάτω, την χρήση οσμοφιλικών ζυμών. Ως οσμοφιλικές ζύμες ορίζονται κάποιες ζύμες οι οποίες έχουν πολύ καλή αντοχή στην οσμοτική πίεση. Το βασικό προιόν της ζύμωσης τους είναι τυπικά μία πολυόλη. Για την γλυκερόλη συγκεκριμένα, οι δύο μικροοργανισμοί που έχουν μελετηθεί το περισσότερο είναι οι Candida krusei και Candida glycerinogenes. Ο δεύτερος έχει σημαντικά καλύτερη παραγωγικότητα για αυτό είναι και αυτός που θα μελετηθεί εν τέλει. Οι μικροοργανισμοί αυτοί τρέφονται μόνο με γλυκόζη για αυτό είναι απαραίτητη μια προκατεργασία για τον διαχωρισμό της κυτταρίνης και ημικυτταρίνης.

* Έκρηξη Ατμού
** Θεωρητικά στοιχεία
  Η μέθοδος της έκρηξης ατμού (steam explosion) θεωρείται μία από τις πιό αποτελεσματικές τεχνικές για pretreatment βιομάζας και διαχωρισμού της στα τρία βασικά της συστατικά την κυτταρίνη, την ημικυτταρίνη και την λιγνίνη.
  
  Βασίζεται στην τροφοδοσία της βιομάζας σε ατμό υψηλής πίεσης και σε θερμοκρασία της τάξης των 200-240 \( ^oC \) για μερικά λεπτά. Έπειτα, απότομη εκτόνωση του μίγματος σε ατμοσφαιρική πίεση που προκαλεί την έκρηξη. Σε αυτό το περιβάλλον, η ημικυτταρίνη η οποία είναι η πιο υδατοδιαλυτή εκ των τριών, διαχωρίζεται σε μεγάλο βαθμό και αυτουδρολύεται, υποβοηθούμενη από το οξικό οξύ που εκλύεται κατά την θερμική επεξεργασία της ημικυτταρίνης. Έτσι, προκύπτει μια υδατοδιαλυτή φάση η οποία είναι κυρίως ημικυτταρινικές ζάχαρες (με βασικό συστατικό την ξυλόζη). Στην φάση αυτή πηγαίνει και ένα κομμάτι της λιγνίνης. Κατά την έκρηξη έχουμε μερικό αποπολυμερισμό της λιγνίνης με αποτέλεσμα να απελευθερώνονται κάποιες υδατοδιαλυτές φαινόλες. Τα δύο συστατικά αυτά διαχωρίζονται με μία εκχύλιση η οποία χρησιμοποιεί κάποιον διαλύτη φαινολών (πχ αιθανόλη).
  
 Η μη υδατοδιαλυτή φάση τώρα (η οποία αποτελείται από κυτταρίνη και μεγάλο ποσοστό της λιγνίνης) διαχωρίζεται και μετά από έκπλυση με νερό ακολουθεί μία εκχύλιση με αλκαλικό διάλυμα (πχ NaOH). Η εκχύλιση αυτή διαχωρίζει την λιγνίνη από την κυτταρίνη καθώς τα προιόντα της λιγνίνης μπορούν να δράσουν ανασχετικά στην υδρόλυση της κυττταρίνης. Για ακόμη καλύτερη απόδοση, κάποιοι συγγραφείς [[cite:&fernandez-bolanosCharacterizationLigninObtained1999]] προτείνουν οξειδωτική κατεργασία της λιγνίνης με χλωριούχα (ClO^{-2}) καθώς έτσι η υδρόλυση της κυτταρίνης επιταχύνεται περαιτέρω (bleaching). Αυτό συμβαίνει διότι η κυτταρίνη είναι πιό προσβάσιμη από το υδρολυτικό ένζυμο (κυτταρινάση) απουσία της λιγνίνης και υπάρχει ένα (μικρό βέβαια) κομμάτι αυτής που είναι αδιάλυτο στο αλκαλικό διάλυμα με το οποίο γίνεται η εκχύλιση.

** Υπολογισμοί για τα δεδομένα μας
  Με βάση την βιβλιογραφία [[cite:&fernandez-bolanosSteamexplosionOliveStones2001]], οι συνθήκες λειτουργίας T = 232 \( ^oC \), P = 26 bar και χρόνος παραμονής t=2 min είναι οι βέλτιστες συνθήκες λειτουργίας. Αυτό είναι διότι στις συνθήκες αυτές ανακτάται το 93.8% της ημικυτταρίνης και το 81.7% της κυτταρίνης. Για τους υπολογισμούς αυτούς έγιναν οι παρακάτω παραδοχές.

  Όλο το υδατοδιαλυτό κλάσμα, πέρα από τις φαινόλες που περιέχει είναι ημικυτταρίνη. Δηλαδή θεωρούμε πως η κυτταρίνη έχει περίπου μηδενική διαλυτότητα στην φάση αυτή. Ακόμη, λόγω της θερμοευαίσθητης φύσης της ημικυτταρίνης, θεωρούμε πως όση δεν διαλύθηκε διασπάστηκε θερμικά και άρα η στερεή φάση δεν έχει κυτταρίνη. Ακόμη, καθώς η λιγνίνη είναι πιο θερμοάντοχη από την κυτταρίνη, θα υποθέσουμε ότι το σημαντικότερο ποσοστό απώλειας στην στερεή φάση οφείλεται στην κυτταρίνη και όχι στην λιγνίνη. Συγκεκριμένα, έγινε η υπόθεση ότι ένα 10% της λιγνίνης διασπάστηκε θερμικά ενώ οι υπόλοιπες απώλειες είναι λόγω της θερμοκής διάσπασςη της κυτταρίνης.

  Υπό αυτές τις παραδοχές, θα ισχύει πως ανακτήθηκαν 49714.8 tn ημικυτταρίνη, 60485.7 tn κυτταρίνη και 30400 tn λιγνίνη. Επίσης, θεωρούμε πως η εκχύλιση της υδατοδιαλυτής φάσης ανακτά όλη την ποσότητα φαινολών (1285.2 tn). Η λιγνίνη που υπάρχει στην στερεή φάση μετά την αλκαλική εχύλιση στην οποία γίνεται η οξειδωτική κατεργασία (bleaching) θεωρούμε πως δεν ανακτάται. Για τα τελικά προιόντα που μας ενδιαφέρουν (γλυκόζη και ξυλόζη), ισχύει πως η γλυκόζη που παράγεται από την υδρόλυση είναι το 30.9% της κυτταρίνης (μέγιστη δυνατή απόδοση με βάση τους [[cite:&fernandez-bolanosCharacterizationLigninObtained1999]] καθώς το δείγμα έχει απολιγνοποιηθεί), δηλαδή 32692.2 tn γλυκόζη ενώ η ξυλόζη είναι το 45.7% της υδατοδιαλυτής φάσης δηλαδή 23307 tn ξυλόζη.

* Χρήση της τεχνικής Organosolv στην προκατεργασία της βιομάζας
  Η τεχνική Organosolv είναι μία αρκετά διαδεδομένη τεχνική προκατεργασίας της βιομάζας. Βασίζεται στην χρήση κάποιου οργανικού διαλύτη (από εκεί βγαίνει και το όνομα organosolv) ο οποίος θα διαλύσει μεγάλο ποσοστό της λιγνίνης και υπό συνθήκες και την ημικυτταρίνη επιτρέποντας τον διαχωρισμό της βιομάζας. Το βασικό ενδιαφέρον που υπάρχει στην διεργασία αυτή είναι ότι ο διαχωρισμός απομακρύνει το σημαντικότερο ποσοστό της λιγνίνης και άρα δεν χρειάζεται να απομακρυνθεί με άλλες τεχνικές όπως παραπάνω. Επίσης, οι διαλύτες που χρησιμοποιούνται μπορούν να είναι πράσινοι, με παραδείγματα όπως την γλυκερόλη την οποία παράγουμε, crude γλυκερόλη που παρατίθεται σε χαμηλή τιμή από τη βιομηχανία του βιοντίζελ [[cite:&sunGlycerolOrganosolvPretreatment2022]] και αιθανόλη (dio βάλε citation εδώ).

  Βέβαια, η organosolv έχει ένα πάρα πολύ σημαντικό μειονέκτημα ότι οι ποσότητες διαλύτη που απαιτούνται είναι πολλαπλάσιες της τροφοδοσίας. Έτσι, θα προκύψει ότι απαιτούνται εκατομμύρια τόνοι διαλύτη για την επεξεργασία της βιομάζας αυτής με organosolv το οποίο μειώνει το οικονομικό εγχείρημα της διεργασίας. Ακόμη, η διεργασία αυτή απομακρύνει κυρίως λιγνίνη με αποτέλεσμα ότι θα χρειαστεί και εδώ έκρηξη ατμού.

  Για αυτό είναι μία ενδιαφέρουσα ιδέα, η οποία όμως θεωρείται μη οικονομικά βιώσιμη.

* Βιοαντιδραστήρας Γλυκερόλης
Όπως προαναφέρθηκε, δώθηκε περισσότερη έμφαση στη χρήση του μικροοργανισμού C. glycerinogenes καθώς σύμφωνα με την βιβλιογραφία [[cite:&zhugeGlycerolProductionNovel2001]] είναι πολύ αποδοτικός στην παραγωγή γλυκερόλης.

** Συνθήκες λειτουργίας και τροφοδοσία βιοαντιδραστήρα
Ένα βασικό δεδομένο που πρέπει να ξέρουμε για τον βιοαντιδραστήρα είναι η τροφοδοσία του και οι συνθήκες λειτουργίας. Τα δεδομένα αυτά αντλήθηκαν με βάση τους [[cite:&zhugeGlycerolProductionNovel2001;&jinByproductFormationNovel2003]] .

Χρησιμοποιήθηκαν ως πηγή άνθρακα 230.44 g/l γλυκόζη και ως πηγή αζώτου 2 g/l ουρία. Επίσης, χρησιμοποιήθηκαν 4 g/l Corn Steep Liquor (CSL) ως ένα επιπλέον θρεπτικό συστατικό που βελτιώνει την απόδοση της μετατροπής σε γλυκερόλη. Το CSL είναι ένα κίτρινο προς καφέ ιξώδη υγρό το οποίο είναι υδατοδιαλυτό. Έχει pH 3.7-4.7 συνήθως και πυκνότητα 1.25 g/ml. Παράγεται από το υγρό άλεσμα του καλαμποκίου. Σε μικροβιακές καλλιέργειες θεωρείται ένα πολύ χρήσιμο πρόσθετο συστατικό καθώς έχει άζωτο (στην μορφή πρωτεινών αλλά και αμμωνίας), φώσφορο και άλλα χρήσιμα συστατικά  [[cite:&liggettCORNSTEEPLIQUOR]]. Μία λεπτομερή ανάλυση των συστατικών του παρατίθεται στον παρακάτω πίνακα με βάση το [[https://www.indiamart.com/proddetail/corn-steep-liquor-15744963191.html][Indiamart]] από το οποίο χρησιμοποιήθηκε και η τιμή του CSL.

#+CAPTION: Σύσταση του CSL με βάση το Indiamart
| Συστατικό     | Σύσταση σε υγρή βάση |
|---------------+----------------------|
| Νερό          |                0.498 |
| Γαλακτικό Οξύ |                0.142 |
| Άζωτο         |               0.0394 |
| Αμινοξέα      |                0.013 |
| Ζάχαρες       |                 0.01 |
| Τέφρα         |               0.0915 |

Οι ουσίες αυτές δεν αθροίζονται στη μονάδα, βέβαια για αυτό είναι σίγουρο πως υπάρχουν και άλλα συστατικά (αυτά αναφέρονται διότι είναι τα βασικότερα). Σύμφωνα με τους [[cite:&zhugeGlycerolProductionNovel2001]], είναι αρκετά σημαντικός και ο φώσφορος στο CSL, τον οποίο προσδιορίζουν στην τάξη του 1%. 

Οι συνθήκες λειτουργίας είναι T = 30 \( ^oC \), ροή αέρα 5 l/min, ανάδευση στα 500 rpm και χρόνος παραμονής 80 h. Τα δεδομένα αυτά προκύπτουν από την βιβλιογραφία ([[cite:&jinByproductFormationNovel2003]]) καθώς στο άρθρο αυτό υπήρχε ένα αναλυτικό διάγραμμα της συγκέντρωσης υποστρώματος, βιομάζας και γλυκερόλης στην διάρκεια της αντίδρασης (Fig. 1). Οι [[cite:&zhugeGlycerolProductionNovel2001]] μελέτησαν τις βέλτιστες συνθήκες λειτουργίας του αντιδραστήρα και θα ήταν ιδανικό να χρησιμοποιούταν αυτό το διάγραμμα, αλλά δεν συμπεριλάμβανε την συγκέντρωση της βιομάζας με αποτέλεσμα να μην μπορεί να προκύψει μία σωστή κινητική μελέτη από τα δεδομένα αυτά.

** Κινητική της αντίδρασης
Καθώς μελετάμε έναν μικροοργανισμό, ένα μοντέλο που περιγράφει πολύ καλά την κινητική του είναι το μοντέλο Monod \[ \frac{dx}{dt} = \frac{μ_{\max }[S]}{K_s + [S]}[x] \] , ή ως προς την κατανάλωση του υποστρώματος \[ \frac{dS}{dt} = \frac{μ_{\max }}{Y_{x / s}} \frac{[S]}{K_S+[S]} [x] \]. Επίσης, έγινε και ένα fitting για την κινητική παραγωγής της γλυκερόλης ως power law expression της συγκέντρωσης του υποστρώματος (\( r_G = \frac{dG}{dt} = k C_S^n \)). Παρακάτω, παρατίθεται και ένας πίνακας με τα δεδομένα που χρησιμοποιήθηκαν.

#+CAPTION: Δεδομένα που χρησιμοποιήθηκαν για την κινητική [[cite:&jinByproductFormationNovel2003]] 
| Time | Glucose (g/l) | Glycerol (g/l) | Biomass (g/l) |
|------+---------------+----------------+---------------|
|    0 |      230.4413 |                |       0.93824 |
|    5 |     228.57485 |                |       2.18008 |
|   10 |     211.91205 |        15.1774 |       5.79464 |
|   15 |      202.3093 |       19.64065 |       8.36496 |
|   20 |      177.7479 |       27.70155 |       10.6936 |
|   25 |     168.84845 |        38.1158 |       10.7544 |
|   40 |      110.6098 |       53.99415 |          10.8 |
|   45 |       86.3189 |       65.19285 |       10.8304 |
|   75 |      22.50795 |       90.18705 |       10.8456 |
|   80 |      13.25685 |        96.1651 |       10.6784 |


Για να γίνει προσαρμογή στα μοντέλα αυτά, πρέπει να προσδιοριστούν οι ρυθμοί. Από τα δεδομένα συγκέντρωσης-χρόνου για βιομάζα, γλυκόζη και γλυκερόλη μπορεί να γίνει προσαρμογή σε απλές πολυωνυμικές καμπύλες, οι οποίες αν παραγωγιστουν δίνουν τους ρυθμούς. Με βάση τα δεδομένα που βρέθηκαν [[cite:&jinByproductFormationNovel2003]], και οι τρείς συσχετίσεις περιγράφονται με R^2 = 0.99 ως παραβολές. Συγκεκριμένα, \( S = 0.008t^2 - 3.531t + 243.428 \) με παράγωγο την \( \frac{dS}{dt} = 0.016t - 3.531 \) και R^2 = 0.99, \( G = -0.007t^2 + 1.758t - 3.428 \) με παράγωγο την \( \frac{dG}{dt} = -0.014t + 1.758 \) και R^2 = 0.996 και \( x = -0.013t^2 + 0.884t - 1.877 \) του οποίου η παράγωγος είναι \( \frac{dx}{dt} = -0.026t+0.884 \) με R^2 = 0.999.

Με βάση τα δεδομένα αυτά έγιναν οι παραπάνω προσαρμογές. Για την προσαρμογή στο μοντέλο Monod, ακολουθήθηκε μία τεχνική παρόμοια του διαγράμματος Lineweaver-Burk για μία ενζυμική αντίδραση. Καθώς για το μοντέλο ισχύει \[ \frac{dx}{dt} = μ[x] \] με \[ μ = \frac{μ_{\max }[S]}{K_s+[S]} \], το μ μπορεί να υπολογιστεί από τον ρυθμό και οι σταθερές μ_max και K_s μπορούν να προσδιοριστούν από την εξίσωση \[ \frac{1}{μ} = \frac{K_s}{μ_{max}S} + \frac{1}{μ_{max}} \] ως κλίση και αποτέμνουσα της γραμμικής εξίσωσης 1/μ - 1/S. Αξίζει βέβαια να σημειωθεί πως το μοντέλο Monod δεν προβλέπει την φάση καθυστέρησης στην ανάπτυξη του μικροοργανισμού. Επιπλέον, παρότι μπορεί να προβλέψει την ύπαρξη στάσιμης φάσης, την προβλέπει όταν η συγκέντρωση του υποστρώματος τείνει στο 0, άρα δεν μπορεί να χρησιμοποιήσει όλα τα δεδομένα της στάσιμης φάσης. Για αυτό, το καλύτερο fit μπορεί να γίνει με τα δεδομένα των χρονικών στιγμών [5, 10, 15, 20].

Το αποτέλεσμα που προέκυψε ήταν η εξίσωση \[ \frac{dx}{dt} = \frac{0.011 [S]}{236.19 + [S]}[x] \]. Για την κατανάλωση του υποστρώματος, θα ισχύει η εξίσωση \[ \frac{dS}{dt} = - \frac{0.0657[S]}{236.19 + [S]}[x] \] η οποία προκύπτει διαιρώντας την παραπάνω με το \( Y_{X / S} = \frac{ΔX}{ΔS} \) για το εύρος των μετρήσεων που χρησιμοποιήθηκαν.

Για την τεχνική κινητική παραγωγής της γλυκερόλης συναρτήσει της συγκέντρωσης του υποστρώματος, μπορούμε να κάνουμε fit στην γραμμική εξίσωση \[ \ln r_G = \ln k + n \ln C_S\]. Από το fitting προκύπτει η εξίσωση \[ r_G = 0.257 [S]^{0.335} \].

Με βάση τα δεδομένα αυτά, μπορούμε να κάνουμε μία εκτίμηση του όγκου του αντιδραστήρα που απαιτείται και της ετήσιας παραγωγής γλυκερόλης. Εφόσον είναι γνωστός ο χρόνος παραμονής και η συγκέντρωση γλυκόζης που εισέρχεται στον αντιδραστήρα μπορεί να υπολογιστεί η κατανάλωση της γλυκόζης ανηγμένη ως προς τον όγκο του αντιδραστήρα [\( \frac{g}{l \cdot year} \)]. Εφόσον είναι γνωστό και το ρεύμα τροφοδοσίας μπορεί να υπολογιστεί πόση μάζα γλυκόζης πρέπει να διαχειριστούμε τον χρόνο. Ο λόγος αυτών των δύο, μας δίνει το απαραίτητο working volume ώστε να επεξεργαστούμε όλη την βιομάζα που έχει η τροφοδοσία χρησιμοποιώντας σε κάθε batch την βέλτιστη συγκέντρωση υποστρώματος. Αυτός προκύπτει ίσος με 1301.5 m^3. Ο συνολικός αντιδρών όγκος άρα πρέπει να είναι στο ελάχιστο 1301.5 m^3, διαμερισμένο μάλλον σε αρκετούς αντιδραστήρες.

* Ανάκτηση της Γλυκερόλης
Έχοντας μελετήσει τον βιοαντιδραστήρα και την κινητική του, μένει να μελετηθεί και πως θα γίνει ο διαχωρισμός της γλυκερόλης από τις υπόλοιπες ουσίες στον αντιδραστήρα. Αρχικά γίνεται μία διήθηση για να διαχωριστεί η βιομάζα από τα υγρά προιόντα. Στην υγρή φάση υπάρχει υδατικό διάλυμα προιόντων και θρεπτικών συστατικών. Το πρώτο βήμα είναι η προσθήκη λιγνίνης στο διάλυμα, η οποία συμπλοκοποιείται με τις αζωτούχες ενώσεις. Έπειτα, ρίχνοντας το pH του διαλύματος, δημιουργείται ίζημα της λιγνίνης η οποία διαχωρίζεται με διήθηση.

Σύμφωνα με τους [[cite:&wallersteinMethodRecoveringGlycerol1946]] αυτή η τεχνική απαιτεί λιγνίνη περίπου ίση κατά μάζα με το συνολικό άζωτο στον αντιδραστήρα. Μην έχοντας κινητικά δεδομένα για την κατανάλωση της ουρίας και του CSL στον αντιδραστήρα, ή την στοιχειομετρία της αντίδρασης που συμβαίνει σε αυτόν, είναι δύσκολο να προβλέψουμε την ποσότητα αζώτου στην έξοδο. Μπορεί να υπολογιστεί αυτή στην είσοδο και να υποθέσουμε μία μετατροπή που θα έχει στον αντιδραστήρα.

Η ουρία έχει χημικό τύπο \( CO(NH_2)_2 \). Με βάση το μοριακό βάρος της και το ατομικό βάρος του αζώτου, βρίσκουμε ότι το 46.667% της ουρίας είναι άζωτο κατά μάζα. Για την κατανάλωση της, ξέρουμε από τους [[cite:&zhugeGlycerolProductionNovel2001]] ότι αν βάλουμε στον αντιδραστήρα 1g/l ουρία, στο τέλος της αντίδρασης θα περίσσεψει πολύ περισσότερη γλυκόζη από ότι αν βάλουμε 2g/l. Αυτό σημαίνει ότι στο 1g/l η ουρία θα ήταν το περιοριστικό υπόστρωμα. Επίσης όμως, αν αυξήσουμε την ποσότητα πάνω από 2 g/l, η απόκριση της αντίδρασης είναι αμελητέα. Άρα στο 2 g/l δεν είναι περιοριστικό υπόστρωμα η ουρία. Απουσία άλλων δεδομένων, θα υποθέσουμε ότι η κατανάλωση είναι μεταξύ του 1 και του 2, άρα έστω περίπου 1.5 g/l. Δηλαδή στο τέλος της αντίδρασης υπάρχουν 0.5 g/l ουρία άρα 0.233 g/l άζωτο.

Για το CSL, σύμφωνα με τους [[cite:&zhugeGlycerolProductionNovel2001]], η παρουσία του παίζει καθοριστικό ρόλο στην ανάπτυξη του μικροοργανισμού, καθώς προσφέρει πολλά θρεπτικά συστατικά. Βέβαια, δεν αποτελεί περιοριστικό υπόστρωμα και η προσθήκη μεγαλύτερης ποσότητας αυξάνει τον ρυθμό λόγω παρουσίας περισσότερων απαραίτητων θρεπτικών συστατικών. Απουσία άλλων πληροφοριών, θα υποτεθεί ότι καταναλώνεται το 50% στην αντίδραση για να γίνουν οι παρακάτω υπολογισμοί. To CSL που έχουμε χρησιμοποιήσει για την κοστολόγηση ([[https://www.indiamart.com/proddetail/corn-steep-liquor-15744963191.html][Indiamart]]) έχει 3.94% άζωτο. Άρα, θα υπάρχουν 0.0788 g/l άζωτο από το CSL.

Στο σύνολο, στην έξοδο του αντιδραστήρα με βάση αυτές τις παραδοχές θα υπάρχει περίπου 0.3121 g/l άζωτο. Με βάση τους υπολογισμούς της κινητικής που έχουν γίνει, ο όγκος του αντιδραστήρα θα είναι 1301.5 m^3, άρα το συνολικό άζωτο που θα υπάρχει στην έξοδο του αντιδραστήρα άνα batch θα είναι 406.21 kg άζωτο. Κάθε χρόνο γίνονται 109 batches με βάση τον χρόνο παραμονής που έχει επιλεχθεί, άρα ετησίως ο αντιδραστήρας έχει στην έξοδο του 44.28 tn άζωτο. Στην πράξη, όμως μπορεί να υπάρχει και ένα μέρος του αρχικού αζώτου το οποίο υπήρχε στο πυρηνόξυλο στον αντιδραστήρα. Θα υποθέσουμε απουσία άλλων δεδομένων πως το άζωτο στο κυτταρινικό κλάσμα είναι το 0.4% της συνολικής τροφοδοσίας, καθώς αυτή είναι η ποσότητα αζώτου που υπάρχει στο πυρηνόξυλο. Πιθανόν να έχει μείνει και λιγότερο από αυτό, αλλά σύμφωνα με τους [[cite:&wallersteinMethodRecoveringGlycerol1946]], μία μικρή περίσσεια λιγνίνης δεν δημιουργέι πρόβλημα.

Άρα, πρέπει να πάρουμε 286.22 tn λιγνίνη (ή και λίγο παραπάνω) από το ρεύμα της για τον διαχωρισμό του αζώτου στην έξοδο του βιοαντιδραστήρα.

Η λιγνίνη αυτή διώχνει τις αζωτούχες ενώσεις και άλλες ακαθαρσίες που υπάρχουν στον αντιδραστήρα. Άρα θεωρούμε πως το προιόν μετά την διεργασία αυτή είναι τα 4 προιόντα, γλυκερόλη, αραβιτόλη, αιθανόλη και οξικό οξύ. Για τον διαχωρισμό αυτό θα χρησιμοποιηθεί απόσταξη. Συγκεκριμένα, θα γίνει μία πρώτη απόσταξη με σκοπό την απομάκρυνση όλου του οξικού οξέος από την υγρή φάση (το οποίο σημαίνει ότι θα απομακρυνθεί και η αιθανόλη καθώς είναι πιό πτητική από το οξικό οξύ). Έπειτα, για τον διαχωρισμό γλυκερόλης και αραβιτόλης πρέπει να ακολουθήσει μία δεύτερη απόσταξη σε ανεβασμένη θερμοκρασία ώστε να πάει σχεδόν όλη η γλυκερόλη στο απόσταγμα. Αυτή η απόσταξη θα υποβοηθάται και από υπέρθερμο ατμό.

Έτσι προκύπτει ένα ρεύμα πρακτικά καθαρής γλυκερόλης το οποίο είναι και το επιθυμητό.

* Οικονομικό Δυναμικό Παραγωγής Γλυκερόλης
 Με βάση τους [[cite:&jinByproductFormationNovel2003]] απαιτούνται 230.44 g/l γλυκόζη, 2 g/l ουρία και 4 g/l Corn Steep Liquor. Ως προιόν θεωρούμε το 96.17 g/l γλυκερόλη. Επίσης, η γλυκόζη είναι από απόβλητα και δεν κοστολογείται. Αξίζει επίσης να αναφερθεί πως η αντίδραση αυτή έχει ως παραπροιόντα την αραβιτόλη, την αιθανόλη και το οξικό οξύ. Με βάση τους [[cite:&zhugeGlycerolProductionNovel2001]], η αντίδραση αυτή παράγει 4.516 g/l αραβιτόλη, 1.19 g/l αιθανόλη και 1.17 g/l οξικό οξύ. Δεν χρησιμοποιήθηκαν δεδομένα από το ίδιο πείραμα για αυτά καθώς η δομή των δεδομένων για την εφαρμογή της στην κινητική από το διάγραμμα στο [[cite:&jinByproductFormationNovel2003]] ήταν πιό βολική, ενώ το προφιλ παραγωγής παραπροιόντων ήταν πιό καλά παρουσιασμένο στο [[cite:&zhugeGlycerolProductionNovel2001]].

Αξίζει να σημειωθεί πως 4 g CSL αντιστοιχούν σε 35.71 mg P, ενώ σύμφωνα με τις βέλτιστες συνθήκες που προσδιόρισαν οι [[cite:&zhugeGlycerolProductionNovel2001]] θέλουμε 55-65 mg P/l. Η πειραματική διαδικασία προέκυψε από την μελέτη [[cite:&jinByproductFormationNovel2003]] και όχι την μελέτη των βέλτιστων συνθηκών επειδή στο άρθρο αυτό αναφερόταν και η συγκέντρωση της βιομάζας η οποία είναι απαραίτητη για μία σωστή κινητική μελέτη.

Για αντιδραστήρα 1301.5 m^3, ο οποίος απαιτείται για την επεξεργασία 32692.2 τόνους γλυκόζη, θέλουμε 283.74 τόνους ουρία και 567.47 τόνους Corn steep liquor. Η παραγωγικότητα είναι 13643 τόνοι γλυκερόλη. Τα παραπροιόντα είναι 640.68 τόνοι αραβιτόλη, 168.82 τόνοι αιθανόλη και 165.99 τόνοι οξικό οξύ το χρόνο. Παρότι τα παραπροιόντα αυτά είναι σε μικρές συγκεντρώσεις, μέσα στα 109 batches που γίνονται το χρόνο και στο working volume των 1301.5 m^3 που χρησιμοποιούμε, οι συνολικές ποσότητες είναι σημαντικές. Άρα, αξίζει να μελετηθεί τι θα γίνουν τα παραπροιόντα αυτά.

Η γλυκερόλη έχει τιμή 721.07 ευρώ ανά τόνο, η ουρία 638.13 ευρώ ανά τόνο ενώ το corn steep liquor 360 ευρώ ανά τόνο.

https://www.echemi.com/productsInformation/pid_Seven41077-glycerol.html

https://www.indiamart.com/proddetail/corn-steep-liquor-15744963191.html

https://tradingeconomics.com/commodity/urea

Ανάγοντας τα στα παραπάνω μεγέθη, το κόστος των πρώτων υλών είναι 181.06 χιλιάδες ευρώ για την ουρία και 204.29 χιλιάδες για το CSL (συνολικό κόστος 385.35 χιλιάδες ευρώ) ενώ το κέρδος είναι 9.84 εκατομμύρια. Άρα, το οικονομικό δυναμικό της διεργασίας είναι 9.45 εκατομμύρια.

Αξίζει να σημειωθεί πως δεν έχουν κοστολογηθεί τα παραπροιόντα επειδή στο παρόν διάγραμμα ροής δεν έχει μελετηθεί ο διαχωρισμός τους για ανάκτηση των καθαρών ουσιών.

* Διάγραμμα Ροής
[[https://github.com/Vidianos-Giannitsis/Process-Design/blob/master/Diagrams/flowsheet_initial.pdf][Εδώ]] μπορείτε να δείτε το διάγραμμα ροής της διεργασίας.

* Βιβλιογραφία
bibliography:~/Sync/My_Library.bib
bibliographystyle:unsrt

