#+TITLE: Process Design Project

This repository hosts various files for my Process Design Project for University for it was recommended we version control the project. Most of the files are in Greek due to it being the language the lesson is taught in.

In the top level folder of the repository are the various .org files (markup format similar to .md) I have which are notes of mine for the project. Since most of my notes reside in my ~/org_roam directory however, it would be bothersome to move them here. With the help of my project [[https://github.com/Vidianos-Giannitsis/zetteldesk.el][zetteldesk.el]] I have created a file (process_design_project_notes.org) which stores all my org_roam notes related to the project. This file is also available in pdf version to leverage all the latex features it uses which Github does not display correctly. Besides those notes, all the other org files in this directory have also been inserted to it as it made sense for me to do so.

In the /Diagrams folder are various .svg files created with Inkscape which are relevant to the project. Some of them are also exported to .pdf or .png

In the /Calculations folder are various Excel and Matlab files used for calculations needed for the project.

In the /Aspen folder are aspen files we have used for simulations of the process.
