#+TITLE: Outline της τελικής εργασίας

Στο αρχείο αυτό θα γραφούν μερικά σχόλια για το πως θα πρέπει να είναι η δομή του τελικού LCA report.

Λογικά θα ξεκινήσουμε με τον σκοπό της μελέτης (assessment της παραγωγής κυκλοπεντανόνης από πυρηνόξυλο). Θα αναφέρουμε πως παράγεται συμβατικά η κυκλοπεντανόνη (το οποίο είναι και η διεργασία με την οποία θα συγκρίνουμε).

Έπειτα, θα μιλήσουμε για το scope της μελέτης (τι συμπεριλαμβάνουμε και τι όχι στη μελέτη), το functional unit αυτής, το LCI που προκύπτει μέσω αυτού και τα impacts τα οποία θα εξετάσουμε. 

Μετά από αυτό μπορούμε να προχωρήσουμε στο πως περάσαμε την διεργασία στο CCalc. Αναφορά σε ότι παραδοχή έγινε και πως διαχειριστήκαμε side streams (waste or coproduct) και τι allocations έγιναν στα coproducts.

Έχοντας εξηγήσει την διεργασία αυτή, μπορούμε να εξηγήσουμε και την διεργασία που χρησιμοποιείται για την σύγκριση αντίστοιχα.

Μετά προχωράμε στο impact assessment. Πρώτα μπορούμε να δείξουμε τα impacts της δικιάς μας διεργασίας, δείχνοντας την συνολική εικόνα, αλλά και τα βασικά hot spots σε κάθε impact. Δείχνουμε πως αυτά τα impacts είναι πολύ χαμηλότερα από την πετρελαική διεργασία (σε όλα εκτός από το water usage) και μετά αρχίζουμε να αναφέρουμε τα προβλήματα της, τα οποία είναι: Δεν έχουμε λάβει υπόψην την παραγωγή της πρώτης ύλης (land use και eutrophication λόγω λιπασμάτων κυρίως, πιθανόν και CF). Βέβαια, χρησιμοποιούμε το απόβλητο της ελιάς, οπότε δεν θα έχουμε πολύ από το burden της διεργασίας εκείνης. Επίσης, έχουμε μεγάλα range αβεβαιότητας. Το οποίο οδηγεί στο επόμενο κομμάτι, που το uncertainty quantification.

Δείχνουμε ποιά είναι τα ranges που θεωρούμε πιθανά και εξηγούμε πως τρέξαμε διαφορετικά σενάρια σε αυτές τις περιοχές. Ακόμη και με όλη την αβεβαιότητα που υπάρχει, η διεργασία μας είναι πολύ καλύτερη, καθώς η παραγωγή του αδιπικού οξέος έχει πάρα πολύ αρνητικό impact. Από την ανάλυση αυτή, προέκυψαν οι γραμμικές εξισώσεις που θα παραθέσουμε, οι οποίες κάνουν πολύ ικανοποιητικά predict τα διάφορα impacts. Με αυτές τις εξισώσεις πάμε από το discrete space στο continuous και μπορούμε να βρούμε το impact για οποιοδήποτε συνδυασμό τιμών στο range που εξετάζουμε (και λογικά κάνουν και extrapolate καλά). Οι συντελεστές της γραμμικής εξίσωσης είναι ουσιαστικά η ευαισθησία του κάθε impact σε κάθε ρυθμιζόμενη μεταβλητή (άρα κάνουμε και ανάλυση ευαισθησίας) και ο συνδυασμός του hot spot και sensitivity analysis μας οδηγεί στα τελικά συμπεράσματα του πως μπορεί να βελτιωθεί με τον ευκολότερο τρόπο η διεργασία.

Γράφουμε τα τελικά συμπεράσματα πως η διεργασία μας δείχνει να είναι καλύτερη από την συμβατική από περιβαλλοντικής άποψης ακόμη και με την αβεβαιότητα που έχουμε και παραθέτουμε τους βασικούς τρόπους βελτίωσης της που προέκυψαν από το hot spot and sensitivity analysis.
