#+TITLE: Ρεύματα, Διεργασίες, Υπολογιστικά και Θερμοδυναμικά Μοντέλα - Σχεδιασμός Διεργασιών
#+AUTHOR: Βιδιάνος Γιαννίτσης
#+LATEX_HEADER: \usepackage[a4paper, margin=3cm]{geometry}
\renewcommand{\abstractname}{Περίληψη}
\renewcommand{\tablename}{Πίνακας}
\renewcommand{\figurename}{Σχήμα}
\renewcommand\listingscaption{Κώδικας}

\begin{abstract}
Στο αρχείο αυτό θα παρουσιαστούν κάποιες πληροφορίες για τις διεργασίες του Steam Explosion και της Βιοαντίδρασης. Αυτές συμπεριλαμβάνουν τα ρεύματα που υπάρχουν και τα υπολογιστικά και θερμοδυναμικά μοντέλα που επιλέχθηκαν για αυτά.
\end{abstract}

* Steam Explosion
To steam explosion είναι η πρώτη διεργασία που χρησιμοποιείται με βάση το διάγραμμα ροής της διεργασίας. Σκοπός του είναι να μπορέσει με χρήση ατμού σε υψηλή πίεση και θερμοκρασία να κάνει ένα πρώτο διαχωρισμό της βιομάζας. Συγκεκριμένα, διώχνει το σημαντικότερο ποσοστό της ημικυτταρίνης η οποία είναι η πιό υδατοδιαλυτή και θερμοευαίσθητη μεταξύ αυτής, της κυτταρίνης και της λιγνίνης.

Το ρεύμα εισόδου είναι 200000 τόνοι πυρηνόξυλο το οποίο ορίστηκε ως ένα Nonconventional component και τα στοιχεία που απαιτούνται για αυτό (proximate & ultimate analysis) βρέθηκαν βιβλιογραφικά [[cite:&koutsomitopoulouPreparationCharacterizationOlive2014;&gonzalezCombustionOptimisationBiomass2004]] 

Στην έξοδο υπάρχουν τρία ρεύματα. Το ένα ρεύμα έχει όλη την κυτταρίνη και τη λιγνίνη οι οποίες δεν διασπάστηκαν θερμικά. Οι ενώσεις αυτές ορίστηκαν στο Aspen ως Nonconventional compounds και τα δεδομένα που απαιτούνται βρέθηκαν από τη βάση δεδομένων [[https://phyllis.nl/Browse/Standard/ECN-Phyllis#][Phyllis2]]. Το δεύτερο είναι η διαλυμένη ημικυτταρίνη που έχει αυτουδρολυθεί στο περιβάλλον της έκρηξης ατμού παράγοντας ξυλόζη, άλλες πεντόζες και εξόζες (καθώς ήταν όλες μικρές ποσότητες, υπολογίστηκαν υποθέτοντας ότι όλες οι ζάχαρες που δεν είναι ξυλόζη στο ρεύμα αυτό είναι αραβινόζη), διάφορες φαινολικές ενώσεις από την διάσπαση της λιγνίνης (για τον ίδιο λόγο θεωρήθηκαν όλες φαινόλη). Η σύσταση του ρεύματος αυτού υπάρχει στην βιβλιογραφία [[cite:&fernandez-bolanosSteamexplosionOliveStones2001]] . Το τρίτο ρεύμα είναι αέριο. Κατά την έκρηξη ατμού, υπάρχει απώλεια μάζας από την τροφοδοσία μέχρι τα δύο παραπάνω ρεύματα εξόδου. Αυτό συμβαίνει διότι η βιομάζα είναι θερμοευαίσθητη και ένα κομμάτι της διασπάται θερμικά. Για να μην γίνει ολοκληρωμένη ανάλυση του κλάσματος που διασπάστηκε, θεωρήθηκε πως όλη η αρχική υγρασία έγινε νερό (το οποίο με βάση την θερμοδυναμική κατανέμεται και στην υγρή και στην αέρια φάση σε ένα βαθμό), όλο το άζωτο της βιομάζας απελευθερώθηκε ως αέριο και οι υπόλοιπες απώλειες αποτελούν παραγωγή CO_2.

Ο αντιδραστήρας του Steam Explosion ορίστηκε ως ένας RYield, καθώς δεν ορίζεται κάποια κινητική για την διεργασία αυτή, αλλά ξέρουμε βιβλιογραφικά τα ρεύματα εξόδου [[cite:&fernandez-bolanosSteamexplosionOliveStones2001;&fernandez-bolanosCharacterizationLigninObtained1999]] . Το θερμοδυναμικό μοντέλο που επιλέχθηκε είναι το μοντέλο SRK καθώς το σύστημα είναι ένα χημικό σύστημα σε υψηλή πίεση και ένα από τα μοντέλα που προτείνει το method assistant του Aspen για τέτοια συστήματα είναι το SRK.

Για περισσότερες πληροφορίες κοιτάξτε το αρχείο [[https://github.com/Vidianos-Giannitsis/Process-Design/blob/master/Aspen/steam_explosion.org][αυτό]] . Το σχετικό αρχείο του Aspen βρίσκεται [[https://github.com/Vidianos-Giannitsis/Process-Design/blob/master/Aspen/steam_explosion_3phases.apwz][εδώ]]. Παρακάτω φαίνονται οι πληροφορίες αυτές και πινακοποιημένες

#+CAPTION: Πληροφορίες σχετικά με την διεργασία της έκρηξης ατμού
|---------------------------------------------|
| Steam Explosion                             |
|---------------------------------------------|
| Θερμοδυναμικό Μοντέλο - SRK                 |
| Μοντέλο Αντιδραστήρα - RYield               |
| Ρεύματα:                                    |
|---------------------------------------------|
| Πυρηνόξυλο                                  |
|---------------------------------------------|
| Μη υδατοδιαλυτή φάση  (Λιγνίνη + Κυτταρίνη) |
|---------------------------------------------|
| Υδατοδιαλυτή φάση. Ημικυτταρινικό           |
| κλάσμα με κύριο συστατικό την ξυλόζη        |
|---------------------------------------------|
| Αέρια (CO_2, N_2, H_2O)                     |
|---------------------------------------------|

** Απορίες
1. Μας ενδιαφέρει να "καθαρίσουμε" το υδατοδιαλυτό ρεύμα ώστε να έχει μόνο ξυλόζη (από την οποία παράγεται η κυκλοπεντανόνη) ή δεν χρειάζεται να ασχοληθούμε.
2. Η προσομοίωση στον RYield τρέχει με Warning πως δεν ισχύουν τα ισοζύγια μάζας για C, H, N. Αυτό είναι πιθανόν να συμβαίνει λόγω συνδυασμού πολλών βιβλιογραφικών δεδομένων (επειδή δεν βρέθηκε άρθρο που να δίνει όλα τα απαιτούμενα δεδομένα). Λόγω αυτού, η προσομοίωση δίνει τα αναμενόμενα αποτελέσματα με το Warning αυτό. Πειράζει να μην ασχοληθούμε περαιτέρω με το warning αυτό καθώς δεν υπάρχει κάποιος εύκολος τρόπος να το ρυθμίσουμε;

* Βιοαντιδραστήρας Παραγωγής Γλυκερόλης
Ο βιοαντιδραστήρας αυτός είναι μία από τις βασικές διεργασίες της εργασίας. Σκοπός του είναι να παράξει γλυκερόλη από γλυκόζη μέσω μικροοργανισμών. Επιλέχθηκε η χρήση του μικροοργανισμού C. glycerinogenes για την διεργασία αυτή και για αυτόν βρέθηκαν δύο βασικά πειράματα τα οποία βοήθησαν στην προσομοίωση του αντιδραστήρα [[cite:&zhugeGlycerolProductionNovel2001;&jinByproductFormationNovel2003]] . Αρχικά έγινε μία απλοποιημένη προσομοίωση όπου υποτέθηκε πως γλυκόζη και οξυγόνο δίνουν γλυκερόλη, διοξείδιο του άνθρακα και νερό και μόλις περάστηκε αυτή στο Aspen, δοκιμάστηκε η προσομοίωση της συνολικής αντίδρασης, όπου λαμβάνει υπόψην την βιομάζα, την πηγή αζώτου και τα παραπροιόντα.

Στην συνολική αυτή αντίδραση, τροφοδοτούμε τον αντιδραστήρα με υδατικό διάλυμα γλυκόζης και ουρίας δεδομένων συγκεντρώσεων καθώς και οξυγόνο. Στην βιβλιογραφία, αναφέρεται πως για την σωστή πραγματοποίηση της αντίδρασης, απαιτείται και κάποιο θρεπτικό μέσο όπως το Corn Steep Liquor. Αυτό είναι ένα "καλά ορισμένο" υγρό αλλά δεν υπάρχει στις βάσεις δεδομένων του Aspen. Ως αποτέλεσμα, πρέπει να περαστεί ως Conventional component όπου θα οριστούν από τον χρήστη όλες οι ιδιότητες του. Αυτό δημιουργεί προβλήματα επειδή κάποιες από τις ιδιότητες που ζητούνται δεν μπόρεσαν να βρεθούν και υποτέθηκαν ίσες με τις αντίστοιχες για το νερό. Η προσομοίωση αυτή έτρεξε με Warning ότι η αντίδραση έχει μη μηδενικό ρυθμό ένω έχει καταναλωθεί όλο το οξυγόνο (το οποίο είναι αντιδρών). Αυτό προκύπτει με το οξυγόνο που τροφοδοτείται για να τρέξει η προσομοίωση χωρίς CSL, το οποίο βρέθηκε αρκετό για να γίνει αντίδραση και να μην έχει πολύ περίσσεια. Σύμφωνα με το warning αυτό, για την αντίδραση με CSL θέλουμε περισσότερο οξυγόνο. Όμως, αν αλλάξει έστω και ελάχιστα η ποσότητα οξυγόνου, το warning αυτό γίνεται 3 errors. Για αυτό, το αρχείο complete_bioreactor δεν το συμπεριλαμβάνει.

Τα προιόντα της αντίδρασης είναι γλυκερόλη (κύριο προιόν της ζύμωσης του C. glycerinogenes), μικροβιακή βιομάζα (η οποία αναπτύσσεται κατά την διάρκεια της αντίδρασης και την αυτοκαταλύει), νερό και διοξείδιο του άνθρακα (απαραίτητα προιόντα της μικροβιακής ζύμωσης) και αιθανόλη και οξικό οξύ τα οποία είναι τα παραπροιόντα της αντίδρασης [[cite:&zhugeGlycerolProductionNovel2001]] . Βιβλιογραφικά παράγεται και αραβιτόλη, αλλά η προσθήκη της αραβιτόλης δημιουργούσε σοβαρά προβλήματα στην προσομοίωση του καθαρισμού της γλυκερόλης για αυτό αποφασίσαμε να αγνοηθεί. Η στοιχειομετρία της αντίδρασης προέκυψε με βάση βιβλιογραφικά δεδομένα για τα yields της αντίδρασης [[cite:&jinByproductFormationNovel2003]] με βάση την μεθοδολογία που περιγράφεται [[https://github.com/Vidianos-Giannitsis/Process-Design/blob/master/bioreactor_stoichiometry.org][εδώ]] . Το δυσκολότερο κομμάτι της προσομοίωσης εδώ ήταν η προσθήκη της μικροβιακής βιομάζας στο Aspen. Με βάση τους [[cite:&wooleyDevelopmentASPENPhysical1996]], βρέθηκε μία τεχνική για να γίνει αυτό, η οποία περιγράφεται με περισσότερη λεπτομέρεια [[https://github.com/Vidianos-Giannitsis/Process-Design/blob/master/biomass_modeling_aspen.org][εδώ]].

Το υπολογιστικό μοντέλο που χρησιμοποιήθηκε για την προσομοίωση του βιοαντιδραστήρα είναι το RBatch καθώς στην βιβλιογραφία ο αντιδραστήρας αυτός είναι batch και υπάρχουν επαρκή δεδομένα για την προσομοίωση αυτή στο Aspen. Ο αντιδραστήρας θεωρήθηκε πως λειτουργεί σε σταθερή πίεση και θερμοκρασία μέχρι το ρεύμα εξόδου να έχει την επιθυμητή ποσότητα γλυκερόλης ή να περάσουν 80 ώρες (βιβλιογραφική διάρκεια αντίδρασης [[cite:&jinByproductFormationNovel2003]] ). Για την κινητική της αντίδρασης, δεν υπάρχει διαθέσιμο στο Aspen το μοντέλο Monod το οποίο χρησιμοποιείται τυπικά για να περιγράψει την κινητική ανάπτυξης ενός μικροοργανισμού. Μπορεί όμως να προσομοιωθεί το μοντέλο αυτό ως LHHW με κατάλληλο ορισμό των παραμέτρων αυτού όπως φαίνεται στο [[https://github.com/Vidianos-Giannitsis/Process-Design/blob/master/Aspen/simplified_bioreactor.org][αρχείο αυτό]].

Για τις θερμοδυναμικές παραμέτρους του προβλήματος χρησιμοποιήθηκε το μοντέλο NRTL-HOC το οποίο είναι κατάλληλο για χημικά συστήματα σε χαμηλή πίεση όπου υπάρχουν οργανικά οξέα. Περισσότερες πληροφορίες για την προσωμοίωση, υπάρχουν [[https://github.com/Vidianos-Giannitsis/Process-Design/blob/master/Aspen/complete_bioreactor.org][εδώ]]. Παρακάτω φαίνονται οι πληροφορίες αυτές και πινακοποιημένες

#+CAPTION: Πληροφορίες σχετικά με τον βιοαντιδραστήρα παραγωγής γλυκερόλης
|-----------------------------------------------------|
| Βιοαντιδραστήρας Παραγωγής Γλυκερόλης               |
|-----------------------------------------------------|
| Θερμοδυναμικό Μοντέλο - NRTL-HOC                    |
| Μοντέλο Αντιδραστήρα - RBatch                       |
| Ρεύματα:                                            |
|-----------------------------------------------------|
| Υδατικό διάλυμα γλυκόζης και ουρίας + οξυγόνο       |
|-----------------------------------------------------|
| Υδατικό διάλυμα γλυκερόλης, βιομάζας, παραπροιόντων |
| και περισσευόμενων θρεπτικών μέσων                  |
|-----------------------------------------------------|

** Απορίες
1. Το ρεύμα εξόδου από τον βιοαντιδραστήρα είναι περίπου 70% νερό κατά μάζα. Για αυτό, σκεφτόμασταν μήπως αξίζει πριν τον καθαρισμό της γλυκερόλης από τα άλλα προιόντα της αντίδρασης να γίνει μία ξήρανση. Αρχικά, πως σας ακούγεται αυτό σαν ιδέα; Όμως, στο Model Palette του Aspen δεν βλέπω κάτι σαν ξηραντήρα άρα ήθελα να σας ρωτήσω και πως μπορούμε να προσομοιώσουμε την ξήρανση στο λογισμικό. Φαντάζομαι πως καθώς η ξήρανση είναι ένα φαινόμενο που έχει κινητική, η προσομοίωση θα γίνει σε έναν αντιδραστήρα, αλλά και πάλι δεν είμαι σίγουρος πως θα το κάναμε αυτό καθώς πως ακριβώς ορίζουμε την "στοιχειομετρία" για κάτι τέτοιο.

** Σχόλια
Η προσομοίωση του βιοαντιδραστήρα δίνει χρόνο λειτουργίας πολύ μικρότερο του βιβλιογραφικού. Αυτό συμβαίνει λόγω παραδοχών που έγιναν κατά τους υπολογισμούς και συγκεκριμένα βασικό πρόβλημα είναι πως έχει υποτεθεί πως παράγεται πολύ περισσότερη βιομάζα από ότι παράγεται πραγματικά, το οποίο αυξάνει πάρα πολύ τον ρυθμό. Εν τέλει όμως, διαπιστώθηκε πως υπάρχουν τα δεδομένα για να βρεθεί ο στοιχειομετρικός συντελεστής της βιομάζας (δηλαδή η ποσότητα βιομάζας στην έξοδο του αντιδραστήρα). Αλλαγή της στοιχειομετρίας της αντίδρασης, θα προκαλέσει αλλαγή στον τύπο της βιομάζας ο οποίος παράγεται, με αποτέλεσμα να πρέπει να ξαναγίνουν αρκετοί υπολογισμοί. Λόγω χρόνου, η προσομοίωση θα διορθωθεί μετά την πρόοδο.

* Απομάκρυνση αζωτούχων από τα προϊόντα της βιοαντίδρασης
Σύμφωνα με τους [[cite:&wallersteinMethodRecoveringGlycerol1946]] , για την πιό αποτελεσματική απόσταξη των προιόντων της ζύμωσης, πρέπει πρώτα να απομακρυνθούν όλα τα αζωτούχα συστατικά στην έξοδο του βιοαντιδραστήρα. Για την διεργασία αυτή δεν βρέθηκαν άλλα δεδομένα, αλλά σύμφωνα με το παραπάνω, απαιτείται λιγνίνη η οποία μπορεί να δημιουργήσει σύμπλοκα με τα αζωτούχα συστατικά και μετά, με οξίνιση του διαλύματος, οι ενώσεις αυτές να δημιουργήσουν ίζημα. Η προσομοίωση της διεργασίας αυτής είναι ιδιαίτερα δύσκολη λόγω της έλλειψης αυτής δεδομένων.

Το ρεύμα εισόδου εδώ είναι όλα τα αζωτούχα συστατικά στην έξοδο (πλην της βιομάζας που είναι εξαρχής στερεή και μπορεί να απομακρυνθεί εύκολα). Αυτά είναι η υπολειπόμενη ουρία και οι πρωτείνες (χάριν ευκολίας μοντελοποιήθηκαν όλες ως αλανίνη, η οποία είναι η επικρατέστερη) και αμμωνία του CSL. Οι ποσότητες πάρθηκαν από την προσομοίωση της βιοαντίδρασης με το CSL παρόλο που αυτή τρέχει με ένα warning.

Το ρεύμα εξόδου θεωρείται πως είναι ένα nonconventional υλικό με τη σύσταση της λιγνίνης αν προστεθεί στη δομή της η κάθε αζωτούχος ένωση. Η διαδικασία των υπολογισμών αυτών περιγράφεται [[https://github.com/Vidianos-Giannitsis/Process-Design/blob/master/Aspen/bioreactor_nitrogen_removal.org][εδώ]].

Ο αντιδραστήρας που χρησιμοποιήθηκε είναι ένας RStoic λόγω των ελάχιστων δεδομένων που υπάρχουν για την αντίδραση. Στο αρχείο που έγιναν οι προαναφερόμενοι υπολογισμοί, έγινε μία προσπάθεια να προκύψει και μία στοιχειομετρία για την αντίδραση, αλλά με βάση τα δεδομένα που μπορούν να περαστούν στο Aspen αυτή δεν έβγαζε σωστά αποτελέσματα. Εν τέλει, η στοιχειομετρία που περάστηκε, περάστηκε μόνο επειδή έβγαζε το αναμενόμενο αποτέλεσμα (παράγεται σύμπλοκο της αζωτούχος ένωσης και της λιγνίνης με μάζα 2 φορές αυτήν της αζωτούχου ένωσης). Το θερμοδυναμικό μοντέλο που χρησιμοποιήθηκε είναι το NRTL. Ακολουθεί και πινακοποιημένη μορφή της προσομοίωσης όπως και παραπάνω

#+CAPTION: Πληροφορίες σχετικά με την απομάκρυνση αζωτούχων
|-------------------------------------------------------------------|
| Απομάκρυνση Αζωτούχων από τον Αντιδραστήρα                        |
|-------------------------------------------------------------------|
| Θερμοδυναμικό Μοντέλο - NRTL                                      |
| Μοντέλο Αντιδραστήρα - RStoic                                     |
| Ρεύματα:                                                          |
|-------------------------------------------------------------------|
| Ουρία, αλανίνη και αμμωνία που περίσσεψαν από τον βιοαντιδραστήρα |
| Λιγνίνη                                                           |
|-------------------------------------------------------------------|
| Σύμπλοκα αζωτούχων και Λιγνίνης                                   |
|-------------------------------------------------------------------|

** Απορίες
1. Λόγω των ελάχιστων δεδομένων που υπάρχουν για την αντίδραση, όπως θεωρώ έγινε κατανοητό, η προσομοίωση δεν ήταν ιδιαίτερα ακριβής ή ολοκληρωμένη. Θεωρείται αξίζει να την λάβουμε υπόψην στο τελικό διάγραμμα ροής, ή δεν αξίζει τον κόπο;

* Γενικές απορίες
1. Προσομοιώνοντας ξεχωριστά την κάθε διεργασία έχουμε επιλέξει διαφορετικά μοντέλα για την κάθε αντίδραση ανάλογα με τις συνθήκες στις οποίες διεξάγονται και τις ενώσεις που παίρνουν μέρος. Έχει χρησιμοποιηθεί SRK για τα συστήματα υψηλής πίεσης (πχ Steam Explosion), NRTL-HOC για τα συστήματα όπου υπάρχει οργανικό οξύ (βιοαντιδραστήρας και καθαρισμός της γλυκερόλης) και NRTL για τα υπόλοιπα. Θεωρείται θα δημιουργήσει πρόβλημα αυτό όταν προσπαθήσουμε να ενώσουμε όλες τις διεργασίες;

* Βιβλιογραφία
bibliography:~/Sync/My_Library.bib
bibliographystyle:unsrt
