* Αντιδραστήρας Σακχαροποίησης
Ο αντιδραστήρας της ενζυμικής σακχαροποίησης αποτελεί την τρίτη
διεργασία στην σειρά, μετά τις διεργασίες έκρηξης ατμού και εκχύλισης με
διάλυμα υδροξειδίου του νατρίου για την αφαίρεση περίσσειας λιγνίνης.

Ως είσοδος θεωρείται το προϊόν της διεργασίας εκχύλισης, δηλαδή η
κυτταρίνη με την λιγνίνη και ένα μεγάλο ποσό νερού που θα χρησιμοποιηθεί
για να διαλύσει την γλυκόζη. Παράλληλα, το ρεύμα εισόδου δεν θεωρείται
πως περιέχει υδροξείδιο του νατρίου για την απλοποίηση των υπολογισμών.
Η λιγνίνη και η κυτταρίνη ορίζονται ως Non-conventional solids στο
Aspen, και τα βιβλιογραφικά δεδομένα τους για τον ορισμό των ιδιοτήτων
βρέθηκαν από την βάση δεδομένων Phyllis
([[https://phyllis.nl/Browse/Standard/ECN-Phyllis]])

Στην έξοδο έχουμε ως υγρό την γλυκόζη που έχει προκύψει από την
σακχαροποίηση και την στερεή κυτταρίνη και λιγνίνη, που θα διαχωριστούν
από το υγρό και θα επιστρέψουν στον αντιδραστήρα για περεταίρω υδρόλυση.
Παράλληλα, εξέρχεται και μια μεγάλη ποσότητα νερού για να διαλύσει την
γλυκόζη.

Παρά το γεγονός πως έχει βρεθεί η κινητική της αντίδρασης ενζυμικής
σακχαροποίησης από την βιβλιογραφία (1) , το μοντέλο αυτό είναι αρκετά
περίπλοκο, και δεν ενδέχεται απλοποίηση και εισαγωγή στο Aspen εύκολα,
κυρίως λόγω της πολυμερικής φύσης της κυτταρίνης. Γι' αυτό το λόγο,
προτιμήθηκε η χρήση βιβλιογραφικών δεδομένων για την εύρεση της απόδοσης
της αντίδρασης, τουλάχιστον μέχρι να μπορέσει να απλοποιηθεί το μοντέλο
σε ικανοποιητικό βαθμό και να οριστεί κατάλληλα η κυτταρίνη. Η απόδοση
της αντίδρασης, σύμφωνα με την βιβλιογραφία, αποδίδει 87.7% γλυκόζη από
την εισαγόμενη κυτταρίνη μετά από παραμονή 72 ωρών. Η λιγνίνη και το
νερό θεωρούνται ως αδρανή.

Για αυτό τον λόγο, ο αντιδραστήρας ορίστηκε ως RYield, καθώς δεν απαιτεί
την εισαγωγή κάποιας κινητικής. Εφόσον το σύστημα λειτουργεί σε χαμηλή
πίεση (1 bar), χρησιμοποιήθηκε το θερμοδυναμικό μοντέλο NRTL, εφόσον
προτάθηκε και από το Method Assistant του Aspen.

Παρακάτω καταγράφονται συνοπτικά οι πληροφορίες αυτής της διεργασίας.

| Διεργασία             | Ενζυμική Σακχαροποίηση                             |
|-----------------------+----------------------------------------------------|
| Είδος Αντιδραστήρα    | RYield                                             |
| Θερμοδυναμικό Μοντέλο | NRTL                                               |
| Ρεύματα:              | Είσοδος: Στερεά (λιγνίνη, κυτταρίνη), Νερό         |
|                       | Έξοδος: Στερεά (λιγνίνη, κυτταρίνη), Νερό, Γλυκόζη |

* Διεργασία Εκχύλισης
Η διεργασία της εκχύλισης ακολουθεί την διεργασία της έκρηξης ατμού, και
αποσκοπεί την διαλυτοποίηση μέρους της λιγνίνης για την διευκόλυνση της
ενζυμικής σακχαροποίησης. Για την εκχύλιση χρησιμοποιείται υδατικό
διάλυμα υδροξειδίου του νατρίου σε 50% κατά βάρος.

Ως είσοδος θεωρείται το κλάσμα λιγνίνης και κυτταρίνης που εξέρχεται από
τον αντιδραστήρα της έκρηξης ατμού και το υδατικό διάλυμα υδροξειδίου,
ενώ ή έξοδος αποτελείται από τα καθαρισμένα στερεά και το διάλυμα
υδροξειδίου που έχει διαλυτοποιήσει μέρος της λιγνίνης.

Για την μοντελοποίηση αυτής της διεργασίας, δεν βρέθηκε κάποια
αντίστοιχη διεργασία στο Aspen Plus, άρα χρησιμοποιήθηκε ο αντιδραστήρας
είδους Swash, ο οποίος μοντελοποιεί την διαδικασία της έκπλυσης στερεού,
και το θερμοδυναμικό μοντέλο που χρησιμοποιήθηκε ήταν το ELECNRTL, το
οποίο προτάθηκε από το Method Assistant του Aspen λόγω ύπαρξης
ηλεκτρολύτη στο νερό.

Διαπιστώθηκε πως στην έξοδο δεν υπήρχε καθόλου διαλυτοποιημένη λιγνίνη
στο ρεύμα εξόδου, το οποίο αποτελούταν εντελώς από νερό και υδροξείδιο
νατρίου. Είναι πιθανό το Aspen Plus, χωρίς δεδομένα για την
διαλυτοποίηση της λιγνίνης, να μην μπορεί να την προσομοιάσει, οδηγώντας
σε αυτήν την αστοχία.

Παρακάτω καταγράφονται συνοπτικά οι πληροφορίες αυτής της διεργασίας.

| Διεργασία             | Εκχύλιση                                                                |
|-----------------------+-------------------------------------------------------------------------|
| Είδος Αντιδραστήρα    | SWash                                                                   |
| Θερμοδυναμικό Μοντέλο | ELECNRTL                                                                |
| Ρεύματα:              | Είσοδος: Στερεά (λιγνίνη, κυτταρίνη), Νερό (Ρεύμα 1)                    |
|                       |                                                                         |
|                       | Υδροξείδιο Νατρίου, Νερό (Ρεύμα 2)                                      |
|                       | Έξοδος: Στερεά (λιγνίνη, κυτταρίνη), Νερό, Υδροξείδιο Νατρίου (Ρεύμα 1) |
|                       |                                                                         |
|                       | Υδροξείδιο Νατρίου, Νερό (Ρεύμα 2)                                      |

* Βιβλιογραφία

#+begin_quote
(1) Kadam, K. L.; Rydholm, E. C.; McMillan, J. D. Development and
Validation of a Kinetic Model for Enzymatic Saccharification of
Lignocellulosic Biomass. /Biotechnol. Prog./ *2004*, /20/ (3), 698--705.
[[https://doi.org/10.1021/bp034316x]].

(2) Fernández-Bolaños, J. Steam-Explosion of Olive Stones: Hemicellulose
Solubilization and Enhancement of Enzymatic Hydrolysis of Cellulose.
/Bioresource Technology/ *2001*, /79/ (1), 53--61.
[[https://doi.org/10.1016/S0960-8524(01)00015-3]].

#+end_quote
