#+TITLE: Εισαγωγή και Συμπεράσματα
#+cite_export: csl american-chemical-society.csl
#+LATEX_HEADER: \usepackage[a4paper, margin=3cm]{geometry}
\renewcommand{\abstractname}{Περίληψη}
\renewcommand{\tablename}{Πίνακας}
\renewcommand{\figurename}{Σχήμα}
\renewcommand\listingscaption{Κώδικας}

* Εισαγωγή
Σκοπός της εργασίας αυτής είναι η αξιοποίηση του πυρηνόξυλου, δηλαδή του ξυλώδους κομματιού του πυρήνα της ελιάς, για την παραγωγή γλυκερόλης και κυκλοπεντανόνης, οι οποίες είναι δύο χρήσιμες οργανικές ενώσεις.

H κυκλοπεντανόνη είναι μία κυκλική οργανική χημική ένωση με μοριακό
τύπο C_{5}H_{8}O και ανήκει στη κατηγορία των οργανικών ενώσεων που
ονομάζονται κετόνες. Συγκεκριμένα, αποτελείται δομικά
από έναν πενταμελή δακτύλιο που περιέχει τη λειτουργική ομάδα των
κετονών. Η φυσική της μορφή είναι ένα άχρωμα υγρό με χαρακτηριστική οσμή
παραπλήσια με μέντα. Η επιθυμία παραγωγής της κυκλοπεντανόνης προέρχεται
από το γεγονός ότι είναι βασικό χημικό ενδιάμεσο προϊόν τόσο στη
φαρμακοβιομηχανία όσο και στην κατασκευή αρωμάτων. Επίσης, είναι
απαραίτητο συστατικό για την κατασκευή εντομοκτόνων και προϊόντων από
καουτσούκ [cite:@yuHighlySelectiveHydrogenative2022]. Ακόμη, χρησιμοποιείται ευρέως ως διαλύτης, για αυτό είναι ενδιαφέρουσα η παραγωγή από πράσινη πρώτη ύλη.

Η κυκλοπεντανόνη παράγεται ως προιόν της φουρφουράλης, η οποία είναι ένα εξαιρετικά χρήσιμο χημικό ενδιάμεσο [cite:@shenProductionCyclopentanoneFurfural2018] μέσω μίας αντίδρασης υδρογόνωσης. Η φουρφουράλη με τη σειρά της παράγεται από το ημικυτταρινικό κλάσμα της βιομάζας και συγκεκριμένα μέσω της όξινης καταλυτικής αφυδάτωσης της ξυλόζης.

Η γλυκερόλη είναι η απλούστερη δυνατή τριόλη, δηλαδή μία οργανική ένωση με τρείς αλκοολομάδες. Έχει μοριακό τύπο C_3H_{8}O_3. Είναι μία ένωση η οποία έχει ευρεία χρήση σε φαρμακοβιομηχανίες, ιδιαίτερα αν ανακτηθεί σε υψηλή καθαρότητα (της τάξης του \( 99.9 \% \)). Επίσης, μπορεί να χρησιμοποιηθεί ως πρώτη ύλη για την παραγωγή πολλών χρήσιμων προιόντων σε ένα πλαίσιο βιοδιυλιστηρίου, για αυτό είναι πολύ ενδιαφέρουσα η μελέτη της παραγωγής γλυκερόλης από βιομάζα, η οποία έχει υψηλή καθαρότητα και διατίθεται σε χαμηλή τιμή [cite:@werpyTopValueAdded2004] .

Η γλυκερόλη είναι μία ένωση η οποία παράγεται σε μεγάλες ποσότητες από την βιομηχανία του βιοντίζελ με πράσινο τρόπο. Λόγω της μεγάλης περίσσειας γλυκερόλης που παράγεται από την διεργασία αυτή, έχει υποτιμηθεί σημαντικά η αξία της. Όμως, η διεργασία αυτή παράγει ακατέργαστη γλυκερόλη αρκετά χαμηλής καθαρότητας, ο καθαρισμός της οποίας είναι πολύ ακριβός και τυπικά δεν συμφέρει την εγκατάσταση. Σε εφαρμογές που απαιτούν πολύ υψηλή καθαρότητα, τυπικά χρησιμοποιείται συνθετικά παραγόμενη γλυκερόλη η οποία παράγεται από προπυλένιο. Για αυτό, υπάρχει αρκετό ενδιαφέρον στην εύρεση μίας διεργασίας η οποία θα παράξει απευθείας γλυκερόλη από βιομάζα σε υψηλή καθαρότητα. Μία τέτοια διεργασία είχε χρησιμοποιήθει στον πρώτο παγκόσμιο πόλεμο για την παραγωγή νιτρογλυκερίνης ως εκρηκτικό, με τον μικροοργανισμό S. cerevisiae. Όμως, σε μεταγενέστερες μελέτες αυτής της αντίδρασης, βρέθηκε πως η απόδοση της διεργασίας αυτής είναι πολύ χαμηλή και δεν αξίζει οικονομικά η κλιμάκωση μίας τέτοιας διεργασίας.

Για αυτό, στην παρούσα μελέτη ασχοληθήκαμε με οσμοφιλικές ζύμες οι οποίες έχουν πολύ υψηλότερη απόδοση στην παραγωγή πολυολών και συγκεκριμένα με την ζύμη Candida glycerinogenes η οποία είναι ιδαίτερα αποδοτική στην παραγωγή γλυκερόλης [cite:@wangGlycerolProductionMicrobial2001; @jinByproductFormationNovel2003; @zhugeGlycerolProductionNovel2001] .

** Ποσότητες
Η προσομοίωση της διεργασίας έγινε θεωρόντας ως τροφοδοσία 200000 tn/y πυρηνόξυλο, η οποία θεωρήθηκε η δυναμικότητα του εργοστασίου. Με βάση την βιβλιογραφία [cite:@domalskiThermodynamicDataBiomass1987; @gonzalezCombustionOptimisationBiomass2004; @fernandez-bolanosCharacterizationLigninObtained1999; @koutsomitopoulouPreparationCharacterizationOlive2014] αυτό σημαίνει πως η θεωρητική ποσότητα κυτταρίνης η οποία υπάρχει σε αυτό είναι 74000 tn/y ενώ η ποσότητα ημικυτταρίνης είναι 53000 tn/y. Από αυτά, μπορεί να διαπιστωθεί μία ψευδοαπόδοση των διεργασιών μετατροπής της κυτταρίνης σε γλυκερόλη και της ημικυτταρίνης σε κυκλοπεντανόνη.

Από τις ποσότητες αυτές, ανακτήθηκαν 27764 tn/y γλυκόζη και 23307 tn/y ξυλόζη με βάση την προκατεργασία που υπέστη η βιομάζα. Η προκατεργασία αυτή βασίστηκε στην έκρηξη ατμού, η οποία είναι μία θερμική μέθοδος στην οποία υπάρχουν σημαντικές απώλειες λόγω θερμικής διάσπασης των πολυμερών. Επίσης, παρότι είναι τα βασικά συστατικά των δύο πολυμερών, δεν μπορεί να ανακτηθεί όλη η ποσότητα τους σε μία τυπική διεργασία.

Τα τελικά μας προιόντα είναι σε ποσότητες 10437 tn/y γλυκερόλη 17765 tn/y κυκλοπεντανόνη, λαμβάνοντας υπόψην όλες τις φυσικές και χημικές διεργασίες που χρησιμοποιήθηκαν, καθώς σε όλες υπάρχει μία απώλεια. Η γλυκερόλη έχει μία σχετικά χαμηλή απόδοση (μόνο το \( 37.6 \% \) της γλυκόζης μετατρέπεται σε γλυκερόλης) λόγω της βιοχημικής διεργασίας που ακολουθήθηκε για την παραγωγή της. Είναι γνωστό πως κατά την ανάπτυξη ενός μικροοργανισμού, η πηγή άνθρακα του - δηλαδή η γλυκόζη - δεν καταναλώνεται μόνο για την παραγωγή χρήσιμων προιόντων, για αυτό δεν αναμένεται πολύ υψηλή απόδοση σε προιόν. Βέβαια, με βάση την βιβλιογραφία είναι από τις καλύτερες δυνατές αποδόσεις που μπορούμε να πετύχουμε. Η κυκλοπεντανόνη, έχει μία αρκετά καλύτερη απόδοση. Το \( 77.8 \% \) της ξυλόζης μετατρέπεται σε κυκλοπεντανόνη, διότι για την μετατροπή αυτή δεν απαιτείται βιοχημική διεργασία, άρα οι αντιδραστήρες μπορούν να λειτουργούν σε πολύ υψηλές μετατροπές.

* Οικονομικό Δυναμικό της Διεργασίας
Πριν γίνει όμως οποιαδήποτε επένδυση, είναι πολύ σημαντικό να υπάρχει μία εικόνα του οικονομικού δυναμικού της διεργασίας. Το οικονομικό δυναμικό είναι μία πρώτη εικόνα των οικονομικών της διεργασίας, λαμβάνοντας υπόψην μόνο το κόστος των πρώτων υλών και τα έσοδα της διεργασίας. Για να αξίζει μία διεργασία, αναμένεται πως το ετήσιο κέρδος της θα είναι αρκετά υψηλό. Στην ολοκληρώμενη οικονομική ανάλυση της διεργασίας, πρέπει να ληφθεί υπόψην και το πάγιο κόστος του εξοπλισμού. Όμως, αυτή η ανάλυση θα γίνει σε μεταγενέστερο στάδιο.

Το θετικό με μία τέτοια διεργασία, η οποία διαχειρίζεται απόβλητα ως πρώτη ύλη είναι ότι οι πρώτες ύλες που απαιτούνται πέραν αυτόν που υπάρχουν ήδη από την βιομάζα είναι λίγες. Για αυτό, το οικονομικό δυναμικό τέτοιων διεργασιών είναι τυπικά αρκετά υψηλό. Στην περίπτωση μας, το μόνο κόστος που υπάρχει πέραν της βιομάζας είναι οι θρεπτικές ουσίες που απαιτούνται για την ανάπτυξη του μικροοργανισμού που παράγει την γλυκερόλη και το υδρογόνο που χρησιμοποιείται για την παραγωγή της κυκλοπεντανόνης, ενώ ως κέρδος υπάρχει η πώληση των δύο προιόντων.

Από την πλευρά της γλυκερόλης άρα, η πώληση της γλυκερόλης επιφέρει κέρδος 8.35 εκατομμύρια ευρώ τον χρόνο ενώ οι θρεπτικές ουσίες που χρειάζονται (ουρία και corn steep liquor) έχουν κόστος 327 χιλιάδες ευρώ. Άρα, το οικονομικό δυναμικό της διεργασίας αυτής είναι περίπου 8 εκατομμύρια ευρώ το έτος. Παρακάτω υπάρχουν και οι πηγές από τις οποίες βρέθηκαν αυτά:

[[https://www.selinawamucii.com/insights/prices/united-states-of-america/glycerol/][Γλυκερόλη: 721 ευρώ ανά τόνο]]

[[https://www.indiamart.com/proddetail/corn-steep-liquor-15744963191.html][Corn Steep Liquor: 360 ευρώ ανά τόνο]]

[[https://tradingeconomics.com/commodity/urea][Ουρία: 638 ευρώ ανά τόνο]]

Από την πλευρά της κυκλοπεντανόνης, η πώληση της επιφέρει κέρδος 92.8 εκατομμύρια το έτος ενώ το υδρογόνο κοστίζει 2.6 εκατομμύρια το έτος με βάση τις τιμές τους στην αγορά. Άρα έχει ένα οικονομικό δυναμικό 90.2 εκατομμύρια ευρώ το έτος. Παρακάτω υπάρχουν και οι πηγές από τις οποίες βρέθηκαν αυτά:

[[https://www.sgh2energy.com/economics][Υδρογόνο: 2 ευρώ ανά κίλο]]

[[https://dir.indiamart.com/impcat/cyclopentanone.html][Κυκλοπεντανόνη: 5.12 ευρώ ανά κιλό]]

Ακόμη, υπάρχει η σκέψη ότι μπορεί το υδρογόνο να παραχθεί με αναμόρφωση της λιγνίνης η οποία είναι διαθέσιμη σε μεγάλη ποσότητα, παράγοντας έτσι υδρογόνο μέσα στη διεργασία και εξαλείφοντας το κόστος αυτό. 

Άρα, το συνολικό οικονομικό δυναμικό της διεργασίας είναι 98.2 εκατομμύρια ευρώ το έτος, το οποίο σημαίνει ότι υπάρχει αρκετό διάστημα για δαπάνες σε ηλεκτρική ενέργεια, βοηθητικές παροχές και εξοπλισμό.

* Συμπεράσματα
Συνοπτικά, μια βασική διαδικασία για την παραγωγή κυκλοπεντανόνης και γλυκερόλης από πυρηνόξυλο έχει σχεδιαστεί, κοστολογηθεί και αναλυθεί με χρήση διάφορων διεργασιων. Η διαδικασία αποδείχθηκε ότι έχει θετικό οικονομικό δυναμικό, με μικρό κόστος πρώτων υλών και είναι φιλική προς το περιβάλλον. Καθώς τα προιόντα αυτά έχουν ζήτηση, ιδιαίτερα για φαρμακοβιομηχανίες, θεωρούμε πως αξίζει να γίνει μία επένδυση στην διεργασία αυτή. Βέβαια, η διεργασία απαιτεί πολύ περισσότερη μελέτη για να είναι ολοκληρωμένη η εικόνα μας για αυτήν.

* Προτάσεις
Το βασικότερο που πρέπει να γίνει είναι μία ολοκληρωμένη οικονομική ανάλυση της διεργασίας, όπου θα κοστολογηθεί ο εξοπλισμός, οι βοηθητικές παροχές και η ηλεκτρική ενέργεια που απαιτείται για την διεργασία έτσι ώστε να αξιολογηθεί καλύτερα η επένδυση.
** Βελτιώσεις στις προσομοιώσεις
Αρχικά, ορισμένες από τις προσομοιώσεις έχουν παραδοχές για την απλοποίηση των προσομοιώσεων οι οποίες στην τελική μελέτη πιθανόν να μπορούν να αρθούν. Έχουν ήδη αναφερθεί παραπάνω μερικές μικρές παραβλέψεις που έχουν γίνει σε ορισμένες προσομοιώσεις, αλλά μία βασική βελτίωση είναι πως πρέπει στην προσομοίωση της κυκλοπεντανόνης (block 600) να οριστεί το πραγματικό ρεύμα ξυλόζης, το οποίο έχει ορισμένες ακαθαρσίες οι οποίες θα δυσχεραίνουν τους διαχωρισμούς της διεργασίας. Επίσης οι εναλλάκτες αυτού του block πρέπει να προσομοιωθούν με χρήση βοηθητικών παροχών και όχι μόνο με το απλό μοντέλο heater.

** Βελτιώσεις στην διεργασία
Επίσης όμως, θα γίνουν και κάποιες βελτιώσεις στην διεργασία. Η βασικότερη θα είναι να γίνει μία ολοκληρωμένη ενεργειακή ολοκλήρωση της διεργασίας και να εκμεταλλευτούν όλα τα ψυχρά και θερμά ρεύματα που έχουμε διαθέσιμα. Επίσης σημαντικό όταν αρχίσουμε να λαμβάνουμε υπόψην τις βοηθητικές παροχές και την ηλεκτρική ενέργεια είναι ότι το block 300 που περιέχει την καύση της λιγνίνης είναι ακόμη σε πρώιμο στάδιο και δείχνει μόνο πως θα παραχθεί ατμός στον λέβητα. Στην πράξη, αυτός ο ατμός μπορεί να χρησιμοποιηθεί σε ένα κύκλο Rankine για παράδειγμα για ηλεκτροπαραγωγή και ταυτόχρονα να μπεί στην διεργασία και μία μονάδα τηλεθέρμανσης για την καλύτερη εκμετάλλευση του. Καθώς η ποσότητα λιγνίνης που ανακτάται είναι αρκετά μεγάλη, η δυναμικότητα του λέβητα είναι υψηλή και μπορεί να καταφέρει να καλύψει μεγάλο ποσό των ενεργειακών και θερμικών αναγκών της εγκατάστασης.

Επίσης, η κυκλοπεντανόνη που παράγεται έχει καθαρότητα 0.98, το οποίο πρέπει να βελτιωθεί, καθώς η κυκλοπεντανόνη που χρησιμοποιείται συνήθως έχει καθαρότητα 0.99. Μία άλλη ενδιαφέρουσα βελτίωση της διεργασίας είναι πως ο μικροοργανισμός που χρησιμοποιείται στην παραγωγή της γλυκερόλης έχει δύο σημαντικά παραπροιόντα, την αιθανόλη και το οξικό οξύ, τα οποία παράγονται σε ποσότητες της τάξης των 140 tn/y. Παρότι μικρές ποσότητες για την κλίμακα της εγκατάστασης, θα μπορούσαν να διαχωριστούν αυτά από το νερό και να πωληθούν, το οποίο είναι ένα σενάριο που μπορεί να εξεταστεί περαιτέρω.
