*  Διάγραμμα ροής και Επεξήγηση
Στο block 500 γίνεται ο καθαρισμός του ρεύματος εξόδου του
βιοαντιδραστήρα παραγωγής γλυκερόλης. Αρχικά το ρεύμα προθερμαίνεται
και ύστερα εκτονώνεται σε έναν flash, στη συνέχεια εισέρχεται σε μία
φυγόκεντρο για την απομάκρυνση της στερέης φάσης, την βιομάζα, και τέλος
μια αποστακτική στήλη για τον τελικό καθαρισμό της γλυκερόλης

* Σχεδιαστικές Επιλογές
Το ρεύμα εξόδου προς καθαρισμό έχει 3 φάσεις, αέρια που είναι \(O_2\)
και \(CO_2\), στερεή που είναι βιομάζα, και υγρή που έχει νερό, οξικό
οξύ, γλυκερόλη, γλυκόζη, ουρία και αιθανόλη. Αρχικά επειδή το ρεύμα
έχει πολύ μεγάλη ποσότητα σε νερό, επιλέχθηκε ένας flash διαχωριστήρας,
εφόσον τα υγρά συστατικά έχουν χαμηλό σημείο βρασμού έως 120 \(^{o} C\)
πέρα από την γλυκερόλη που έχει σημείο βρασμού στους 290\(^{o} C\).
Παρακάτω παρουσιάζονται οι συνθήκες λειτουργίας στον flash.\\

- Θερμοκρασία εισόδου ρεύματος: 150 \(^{o} C\)

- Θερμοκρασία λειτουργίας: 140 \(^{o} C\)

- Πίεση λειτουργίας: 1 atm

Η πίεση παραμένει στη 1atm εφόσον δεν υπάρχει λόγος να αλλάξει εφόσον
υπάρχει μεγάλη διαφορά στα σημεία βρασμού μεταξύ του προιόντος και των
άλλων συστατικών. Η θερμοκρασία προθέρμανσης και λειτουργίας επιλέχθηκαν
έτσι ώστε να μην είναι αρκετά υψηλή για να υπάρξουν απώλειες σε
γλυκερόλη αλλά ούτε αρκετά χαμηλή που να παραμένει μεγάλη ποσότητα
νερού επειδή έτσι καθιστά πιο ενεργοβόρα και κοστοβόρα την απόσταξη
αργότερα. Μετά απο διάφορες δοκιμές επιλέχθηκαν αυτές οι θερμοκρασίες
για τους παραπάνω λόγους.\\
Στη συνέχεια το ρεύμα εισέρχεται σε μια φυγόκεντρο τύπου decanter για
την πλήρη απομάκρυνση της στερεής φάσης του ρεύματος.\\
Τέλος το ρεύμα καταλήγει σε μια αποστακτική στήλη για να απομακρυνθεί το
υπόλοιπο νερό ώστε να καθαριστεί πλήρως η γλυκερόλη, παράλληλα σε
αυτή την διεργασία απομακρύνεται όλη η εναπομένουσα αέρια φάση. Παρακάτω
παρουσιάζονται οι συνθήκες λειτουργίας στην αποστακτική στήλη τύπου
Radfrac.

- Θερμοκρασία εισόδου ρεύματος: 140 \(^{o} C\)

- Θερμοκρασία λειτουργίας: 140\(^{o} C\)

- Πίεση κορυφής: 0,95 atm

- Πίεση πυθμένα:1,05 atm

- Βαθμίδες: 6

- Βαθμίδα τροφοδοσίας: 3

- Λόγος αναρροής: 0,175

- Λόγος αποστάγματος πρός παροχή: 0,366065

Η επιλογή των χαρακτηριστικών της στήλης έγιναν με βάση μια πρώτη
προσομοίωση με στήλη dstwu, ύστερα με βάση τα αποτελέσματά της έγινε
προσομοίωση σε radfrac. Η θερμοκρασία εισόδου και λειτουργίας δεν υπήρχε
λόγος να μεταβληθεί, όπως και η πίεση λειτουργίας λόγω της μεγάλης
διαφοράς στα σημεία βρασμού των υγρών συστατικών.

* Προσομοίωση στο Aspen
Από τον βιοαντιδραστήρα παράγονται 13001 τόννοι γλυκερόλης τον
χρόνο, και από το τελικό ρεύμα ανακτούνται 11722 τόνοι, που αποτελεί το
90%, δηλαδή χάνεται το 10% της παραγόμενης γλυκερόλης στα αέρια
ρεύματα του flash και της αποστακτικής. Επίσης το τελικό ρεύμα
γλυκερόλης έχει καθαρότητα 99,99%.

* Ενεργειακή Ολοκλήρωση
Η προθέρμανση του ρεύματος επιτυγχάνεται εξ ολοκλήρου από τα θερμά
ρεύματα της διεργασίας. Αρχικά το καθαρό ρεύμα γλυκερόλης, εξέρχεται
από την στήλη στους 290\(^{o} C\) , το οποίο είναι ακατάλληλο για
αποθήκευση σε κάποια δεξαμενή, για αυτόν τον λόγο χρησιμοποιείται για
προθέρμανση του ρεύματος για την είσοδο στο flash, όμως λόγο της χαμηλής
θερμοχωρητικ΄ποτητας της δεν μεταβάλλει την θερμοκρασία. Συνεπώς πρέπει
να αξιοποιηθούν τα αέρια ρεύματα του flash και της αποστακτικής στήλης.
Όμως επειδή αυτά βρίσκονται σε πίεση 1 atm όπως και το ψυχρό ρεύμα, δεν
επιτυγχάνεται επαρκή θέρμανση , όμως αν γίνει συμπίεση του θερμού
ρεύματος στις 2atm, ολοκληρώνεται η προθέμρανση του ρεύματος.
