#+TITLE: Δομή της παρουσίασης του μαθήματος

Αυτό είναι ένα πρόχειρο αρχείο που αναφέρει συνοπτικά μερικές ιδέες για την δομή της παρουσίασης και του συνοδευτικού αρχείου.

* Εισαγωγή
Είναι μία καλή ιδέα να ξεκινήσουμε την παρουσίαση με μία εισαγωγή του θέματος. Να εξηγήσουμε δηλαδή τα βασικά σημεία του θέματος, όπως ποιά είναι η πρώτη ύλη, ποιά είναι τα προιόντα κλπ. Θα είναι μάλλον ενδιαφέρον να εξηγήσουμε στο section αυτό γιατί θέλουμε να παράξουμε αυτά τα προιόντα και ποιό περιμένουμε να είναι το market μας. Με βάση αυτά, θα δείξουμε και τους υπολογισμούς του οικονομικού δυναμικού για το αν αξίζει ή όχι σε πρώτη εικόνα η διεργασία.

Μετά, μπορούμε να εξηγήσουμε ότι ιδέες υπάρχουν για τις μετατροπές και να πούμε ότι εμείς καταλήξαμε σε αυτήν την διεργασία για τους x, y λόγους. Έτσι, καταλήγουμε στο ότι έχουμε εισάγει τον σκοπό της διεργασίας, γιατί είναι σημαντικός και πως μπορούμε να τον επιτεύξουμε.

* Ορισμός της Διεργασίας
Έχοντας εισάγει την διεργασία, μπορούμε να αρχίσουμε να μπαίνουμε πιο in-depth σε αυτήν. Αρχικά, χωρίζουμε την διεργασία σε 4 κομμάτια. Προκατεργασία της βιομάζας και διαχωρισμός των τριών βασικών κλασμάτων της ως το πρώτο (blocks 100, 200). Παραγωγή γλυκερόλης από γλυκόζη (blocks 400, 500). Παραγωγή κυκλοπεντανόνης από ξυλόζη (blocks 600, 700). Ατμολέβητας με καύσιμο την λιγνίνη (block 300).

Έχοντας εισάγει το ποιά είναι η δομή της διεργασίας, μπορούμε να αρχίσουμε να μιλάμε για το κάθε block ξεχωριστά. Είναι μία εύλογη ιδέα να ξεκινήσουμε από τα sections των δύο προιόντων τα οποία είναι τα πιό σημαντικά, μετά να μιλήσουμε για την προκατεργασία για να δούμε πως θα φτάσουμε στις πρώτες ύλες που απαιτούν τα προιόντα μας από την πρώτη ύλη που έχουμε και στο τέλος να αναφερθεί η λιγνίνη.

* Μελέτη του κάθε block
Για το κάθε block μπορούμε να παραθέσουμε τα εξής:

** Διάγραμμα ροής του block
Είτε μόνο αυτό στο Aspen ή για το extra flex πρώτα ένα conceptual με ζωγραφική και μετά η προσομοίωση.

** Επεξήγηση του διαγράμματος ροής
Μάλλον χωρίς πολλές λεπτομέρειες, απλώς ποιός είναι ο σκοπός του, τι μπαίνει τι βγαίνει και πως προσομοιώθηκε στο Aspen η κάθε μονάδα. Στην παρουσίαση δεν πρέπει να υπάρχει μεγάλο κείμενο για αυτό, πέρα από ίσως ένα υπόμνημα καθώς η επεξήγηση θα γίνει προφορικά. Στο κείμενο καλό είναι να υπάρχουν περισσότερα σχόλια.

** Σχεδιαστικές επιλογές
Γιατί επιλέχτηκε αυτός ο διαχωρισμός ή αυτός ο τύπος αντιδραστήρα για την διεργασία και γιατί λειτουργεί στις συνθήκες αυτές. Γιατί επιλέχτηκε ένα μοντέλο και όχι ένα άλλο. Επειδή αυτό θεωρείται το πιό σημαντικό κομμάτι μάλλον θα δώσουμε αρκετή έμφαση εδώ.

** Υπολογισμοί
Μπορούμε με έναν ωραίο και συνοπτικό τρόπο να περιγράψουμε τους βασικούς υπολογισμούς του block είτε αυτοί έγιναν στο χέρι ή μόνο στο Aspen. Επίσης σε αυτό το section μπορεί να αναφερθούν περισσότερες λεπτομέρειες της προσομοίωσης οι οποίες είναι λιγότερο σημαντικές από αυτές που ειπώθηκαν παραπάνω. Για την παρουσίαση αυτό πρέπει να είναι αρκετά μικρό για να μην είναι κουραστικό, ενώ στο κείμενο ίσως είναι λίγο πιό αναλυτικό.

Έχοντας κάνει αυτή τη μελέτη για το κάθε block, πρακτικά έχουμε περιγράψει πλήρως όλη την διεργασία μας 
