#+TITLE: Προσομοίωση του καυστήρα λιγνίνης

Η καύση της λιγνίνης είναι ένα σημαντικό κομμάτι της διεργασίας μας. Παράγει θερμά καυσαέρια από τα οποία μπορεί να παραχθεί ατμός για να θερμάνει άλλα ρεύματα της διεργασίας. Η λιγνίνη που έχουμε διαθέσιμη είναι 5169.33 kg/hr. Για την προσομοίωση, θα υποτεθεί η λιγνίνη με βάση τους [[cite:&wooleyDevelopmentASPENPhysical1996]], της οποίας η ανάλυση έχει γίνει στο αρχείο lignin_cellulose_conventionals.org. Με το μοριακό βάρος της (122.493), η μολαρική ροή λιγνίνης είναι 42.2 kmol/hr.

Η αντίδραση καύσης που θεωρούμε είναι η
\[ C_{7.3}H_{13.9}O_{1.3} + 10.125O_2 \rightarrow 6.95 H_2O + 7.3CO_2  \] η οποία είναι πρώτης τάξης ως προς την λιγνίνη με ενέργεια ενεργοποίησης 46.68 kJ/mol και προεκθετικό παράγοντα 12.96 h^{-1} ή 0.216 min^{-1} ή 3.6e-3 s^{-1} [[cite:&farrokhThermogravimetricAnalysisLignin2019]] . Η αντίδραση θα γίνει σε αντιδραστήρα συνεχούς ροής τύπου CSTR καθώς θέλουμε συνεχή ροή ατμού για θέρμανση των άλλων διεργασιών μας.

Ο αντιδραστήρας θα λειτουργεί σε πίεση 1 bar (σε πρώτη φάση) ορίζοντας το heat duty, καθώς γνωρίζουμε πως η θερμογόνος δύναμη της λιγνίνης είναι 23.5 MJ/kg και τροφοδοτούμε με 5169.33 kg/hr. Άρα 33.744 MW θερμότητα. Επίσης, ο αντιδραστήρας πρέπει να λειτουργεί με μία περίσσεια αέρα. Στη μελέτη των [cite:@gonzalezCombustionOptimisationBiomass2004] για την καύση πυρηνόξυλου υπολογίστηκε πως χρειάζεται ένα λ = 2.5. Άρα, η παροχή οξυγόνου θα είναι 25 φορές η μολαρική παροχή λιγνίνης και επειδή στην πράξη χρησιμοποιούμε αέρα και όχι οξυγόνου, πρέπει να βάλουμε και 3.76 φορές το οξυγόνο σε άζωτο. Άρα, το άζωτο θα έχει παροχή 95 φορές την παροχή λιγνίνης. Αυτές οι τιμές αντιστοιχούν σε 1068.2 kmol/hr οξυγόνο και 4016.4 kmol/hr άζωτο. Στα προιόντα της καύσης θα αγνοήσουμε την παρούσια NOx και θα πούμε ότι παράγεται μόνο νερό και διοξείδιο του άνθρακα πέρα από την περίσσεια αέρα.

Έπειτα, τα καυσαέρια αυτά θα θερμαίνουν ένα ρεύμα νερού σε υψηλή πίεση (θα υποτεθεί νερό στα 4 MPa καθώς αυτή είναι μία τυπική πίεση για ατμό υψηλής πίεσης σε ατμολέβητα) για παραγωγή ατμού υψηλής πίεσης ο οποίος θα χρησιμοποιηθεί οπουδήποτε χρειάζεται μία θερμή παροχή στη διεργασία. Η παροχή αυτού θα βρεθεί στο Aspen μέσω ενός design spec (ή και με διάφορες δοκιμές) έτσι ώστε να εκμεταλλευόμαστε όση περισσότερη θερμική ενέργεια των καυσαερίων μπορούμε. Ο εναλλάκτης θα σχεδιαστεί για δεδομένη θερμοκρασία εξόδου του θερμού ρεύματος και η παροχή θα χρησιμοποιηθεί θα είναι επαρκής ώστε να παράγεται ελαφρώς υπέρθερμος ατμός (ο κορεσμός είναι στους 250.4 \( ^oC \)), το παράγουμε στα 259 \( ^oC \). Πρέπει να οριστεί η θερμοκρασία εξόδου του θερμού επειδή τα καυσαέρια δεν μπορούν να ψυχθούν μέχρι θερμοκρασία δωματίου. Βασικό πρόβλημα γενικότερα είναι το όξινο σημείο δρώσου των καυσαερίων το οποίο δεν μας αφήνει να πέσουμε κάτω από 150 \( ^oC \) τυπικά. Το πυρηνόξυλο είναι ένα υλικό με σχεδόν μηδενικό θείο, άρα αυτό μπορεί να παραλειφθεί. Όμως, σε πολύ χαμηλές θερμοκρασίες, μπορεί και το NOx που αγνοούμε στην ανάλυση μας αλλά υπάρχουν σίγουρα να δημιουργήσουν νιτρικό οξύ το οποίο είναι προβληματικό. Ακόμη, υπάρχει και ο παράγοντας ότι τα καυσαέρια πρέπει να είναι σε μία υψηλότερη θερμοκρασία για να ευνοείται ο ελκυσμός του λέβητα και να μην κολλάει CO_2 και μπλοκάρει την παροχή του αέρα. Άρα, μπορούμε να κάνουμε μία πιό αισιόδοξη πρόβλεψη από το 150 \( ^oC \) αλλά και πάλι σίγουρα όχι κάτω από 100 \( ^oC \). Έστω ότι βγαίνουν στους 110 \( ^oC \).

Τέλος, ο ατμός υψηλής πίεσης που θα παραχθεί μπορεί να μπεί σε έναν απλό εναλλάκτη και να θέσουμε να ψυχθεί σε θερμοκρασία δωματίου για να δούμε το heat duty του αντίστοιχου εναλλάκτη. Έτσι, μπορούμε να ξέρουμε πόση θερμική ενέργεια μπορούμε να προσφέρουμε στο σύστημα μας.
