#+TITLE: Προσωμοίωση του βιοαντιδραστήρα στην απλούστερη δυνατή μορφή

Το αρχείο αποτελεί το documentation της προσωμοίωσης του βιοαντιδραστήρα του C. glycerinogenes στην απλούστερη δυνατή του μορφή. Για την προσωμοίωση αυτή υποτέθηκε πως μόνο υπόστρωμα είναι η γλυκόζη, δεν υπάρχουν παραπροιόντα και δεν παράγεται βιομάζα. Άρα, μελετάται η αντίδραση \( 1.22 C_6H_{12}O_6 + 3.82O_2 \rightarrow C_3H_8O_3 + 4.32CO_2 + 3.32H_2O \). Αρχικά ορίστηκαν τα συστατικά αυτά στο aspen (μαζί με το Ν_2 καθώς δεν τροφοδοτούμε καθαρό οξυγόνο αλλά αέρα στον αντιδραστήρα). Ως μέθοδος επιλέχθηκε η NRTL η οποία είναι κατάλληλη για χημικά συστήματα σε χαμηλές πιέσεις και τα συστατικά οξυγόνο, διοξείδιο του άνθρακα και άζωτο ορίστηκαν ως henry components για να ληφθεί υπόψην η διαλυτότητα του στο νερό.

Έπειτα, ορίστηκε το ρεύμα τροφοδοσίας στις συνθήκες λειτουργίας του αντιδραστήρα (30 \( ^oC \), 1 bar) με τροφοδοσία σε kmol/hr. Υπολογίστηκε αρχικά η τροφοδοσία ανά ώρα της γλυκόζης (στο αρχείο bioreactor_stoichiometry.m που χρησιμοποιήθηκε για την στοιχειομετρία έχουν υπολογιστεί μολαρικές ροές) και με βάση αυτήν, υπολογίστηκε το στοιχειομετρικά απαιτούμενο οξυγόνο. Όμως, επειδή το οξυγόνο δεν συμμετέχει στον ρυθμό της αντίδρασης, αν έχουμε το στοιχειομετρικά απαιτούμενο το άσπεν θα βγάλει error ότι δεν υπάρχει οξυγόνο στον αντιδραστήρα αλλά ο ρυθμός δεν είναι 0. Για αυτό, η τροφοδοσία οξυγόνου τέθηκε λίγο πάνω από την στοιχειομετρική ποσότητα για να αποφευχθεί αυτό. Το άζωτο υπολογίστηκε από την μοριακή αναλογία N_2, O_2 στον αέρα.

Έπειτα ορίστηκε ο αντιδραστήρας ως ένας RBatch που λειτουργεί σε σταθερή θερμοκρασία 30 \( ^oC \) και πίεση 1 bar με χρόνο λειτουργίας 80 h. Για την κινητική στον αντιδραστήρα υπήρξε το πρόβλημα ότι το σύστημα θα έπρεπε να περιγράφεται από μία κινητική τύπου Monod, αλλά το Aspen δεν έχει το μοντέλο αυτό. Διαπιστώθηκε όμως πως το μοντέλο LHHW και το μοντέλο Monod έχουν κάποιες ομοιότητες. Η κινητική της αντίδρασης με την παραπάνω στοιχειομετρία μπορεί να οριστεί με το μοντέλο LHHW θέτοντας k=1, E=0 (το φαινόμενο k στον αριθμητή το οποίο στην περίπτωση μας θα είναι 0), μετά στο Driving Force να οριστεί ένας όρος της μορφής \( μ_{\max }[S] \) δηλαδή πρώτης τάξης ως προς την συγκέντρωση της γλυκόζης η οποία έχει ως συντελεστή της σταθερά μ_max του μοντέλου και στο Adsorption να οριστεί ένας πρώτος όρος για τον οποίο το [S] έχει συντελεστή 0 ενώ ο σταθερός όρος είναι K_s και μία δεύτερη για την οποία το [S] έχει συντελεστή μονάδα και τίποτα άλλο. Πολύ σημαντικό για τον σωστό ορισμό του προβλήματος είναι να αναφερθεί στο driving force ότι οι μονάδες συγκέντρωσης που χρησιμοποιούνται είναι μαζική συγκέντρωση. Επίσης σημαντικό είναι όλα τα μεγέθη να χρησιμοποιούν μονάδες SI. Δηλαδή το μ_max να είναι σε αντίστροφα δευτερόλεπτα και οι συγκεντρώσεις σε kg/m^3. Βέβαια, για το δεύτερο, το g/l είναι ισοδύναμο της μονάδας του SI άρα δεν υπάρχει πρόβλημα στη χρήση του. Σημείωση ότι το Aspen θέλει το ln του συντελεστή άρα στον πρώτο όρο μπαίνει ln(K_s) και στον δεύτερο 0 αλλά εκθέτης του [S] μονάδα. Έτσι, διαμορφώνεται ένα μοντέλο LHHW το οποίο είναι της μορφής \[ \frac{1 \cdot μ_{\max }S}{K_s+S} \] το οποίο είναι στην πραγματικότητα η ειδική ταχύτητα του μοντέλου Monod. Για να ορίσουμε το ολοκληρωμένο μοντέλο Monod, θα πρέπει στο Driving Force να συμπεριληφθεί και ένας όρος συγκέντρωσης της βιομάζας. Αλλά επειδή στον απλοποιημένο αυτό σχεδιασμό έχει αγνοηθεί η ύπαρξη βιομάζας, δεν λήφθηκε υπόψην.

Τρέχοντας το σύστημα αυτό, θα προκύψουν τα αποτελέσματα της προσωμοίωσης. Αξίζει να αναφερθεί πως αν δούμε το προφιλ της μάζας της κάθε ένωσης με τον χρόνο φαίνεται πως σε 80 h, δεν έχουμε φτάσει ούτε 50% της μετατροπής της γλυκόζης. Αυτό που λείπει, είναι προφανώς η βιομάζα. Μόλις εισαχθεί στο μοντέλο και η βιομάζα, τα αποτελέσματα δύνανται να είναι αρκετά διαφορετικά καθώς η συγκέντρωση της βιομάζας αυξάνει τον ρυθμό και η βιομάζα αποτελεί προιόν της αντίδρασης. Άρα, έχουμε προσωμοιάσει την βιοχημική αντίδραση (η οποία είναι μία αυτοκαταλυτική αντίδραση) χωρίς να λάβουμε υπόψην την αυτοκατάλυση. Για αυτό είναι απόλυτα λογικός ο πολύ μικρός βαθμός μετατροπής που προκύπτει.

Έπειτα, έγινε και μία δοκιμή καθαρισμού της γλυκερόλης. Με ένα flash, μπορούμε να διώξουμε τα αέρια και να μείνει στο διάλυμα νερό, γλυκερόλη και αέρια στη διαλυτότητα τους στο νερό (έχει υπολογιστεί από το Aspen εφόσον ορίστηκαν ως Henry compounds). Στο απλό αυτό σενάριο, μπορεί να γίνει μία απόσταξη του μίγματος για περαιτέρω καθαρισμό της γλυκερόλης (και αν έχω χρόνο θα την δοκιμάσω με τις κολώνες DSTWU και Radfrac). Στο πραγματικό σενάριο, θα γίνει όντως flash για να φύγουν τα αέρια και μετά μάλλον 2 αποστάξεις για να διώξουμε τα παραπροιόντα, καθώς και μία διήθηση για την απομάκρυνση της βιομάζας και αντίδραση με λιγνίνη για απομάκρυνση του αζώτου στον αντιδραστήρα. Το flash θα διώξει τη μεγαλύτερη ποσότητα αερίων, αλλά θα υπάρχουν ακόμη στο υγρό ρεύμα αέρια σε ποσότητα ίση περίπου με τη διαλυτότητα τους στο νερό. 

Επόμενο στάδιο της προσωμοίωσης (πέρα από τις περαιτέρω δοκιμές απόσταξης στο απλό παράδειγμα αυτό) πρέπει να είναι η προσθήκη των παραπροιόντων στην αντίδραση με βάση την στοιχειομετρία τους αγνωόντας ακόμη σε πρώτη φάση την βιομάζα, την ουρία και το CSL. Αν γίνει αυτό, με το flash που διώχνει τα αέρια, μπορεί κάποιος άλλος να προχωρήσει στους διαχωρισμούς του μίγματος εξόδου που θα είναι ακόμη καλύτερα ορισμένο επειδή θα έχει λάβει υπόψην και τις απώλειες στο flash. Έπειτα, μόλις βρούμε πως εισάγεται η βιομάζα στο Aspen, πρέπει να γίνει η προσωμοίωση του συνολικού μοντέλου του βιοαντιδραστήρα χωρίς πολλές παραδοχές. Αν τελειώσω νωρίς με αυτό, θα ασχοληθώ περαιτέρω και με όποιους διαχωρισμούς δεν έχουν μελετήσει οι υπόλοιποι.
