#+TITLE: Προσομοίωση του Steam Explosion με Conventional solids

Η προσομοίωση του Steam Explosion με την κυτταρίνη και την λιγνίνη ως nonconventionals βγάζει error στα mass balances ακόμη και αν προσπαθήσουμε να τα φτίαξουμε (/Calculation/steam_explosion_yields.ods). Για αυτό, στο αρχείο αυτό θα γίνει μία προσπάθεια να προσομοιώσουμε τα δύο αυτά ως conventionals σύμφωνα με τους [[cite:&wooleyDevelopmentASPENPhysical1996]] για να δούμε αν θα τρέξει η προσομοίωση.

Σύμφωνα με αυτούς, η κυτταρίνη αντιστοιχεί σε ένα πολυμερές με δομική μονάδα το μόριο \( C_6H_{10}O_5 \) για αυτό θα χρησιμοποιηθεί η ένωση αυτή. Για την λιγνίνη υποτέθηκε ο τύπος \( C_{7.3}H_{13.9}O_{1.3} \). Οι αντίστοιχες αντιδράσεις καύσης είναι οι
\[ \begin{align*} C_6H_{10}O_5 + 6O_2 \rightarrow 5H_2O + 6CO_2 \\ C_{7.3}H_{13.9}O_{1.3} + 10.125O_2 \rightarrow 6.95 H_2O + 7.3CO_2   \end{align*} \]

Για την κυτταρίνη, το μοριακό βάρος υπολογίζεται άμεσα για τη δομική μονάδα (162.144). Η θερμότητα σύνθεσης βρέθηκε βιβλιογραφικά [[cite:&domalskiThermodynamicDataBiomass1987]] ως 17.456 kJ/g. Για την θερμοχωρηστικότητα, βρέθηκε από τους [[cite:&wooleyDevelopmentASPENPhysical1996]] ότι για Τ = 298.15 Κ, CP_s = -0.117e+5 και για Τ = 1000 K, CP_s = 0.672e+3. Η πυκνότητα θεωρήθηκε 1.5 g/cc (ίδια με του αμύλου). Άρα, 0.667 cc/g αν θέλουμε ειδικό όγκο.

Για την λιγνίνη, το μοριακό βάρος υπολογίζεται και εδώ άμεσα (122.493). Η θερμότητα σύνθεσης βρέθηκε συγκεκριμένα για πυρηνόξυλο ως 23.5 MJ/kg (2.8786 kJ/kmol) από τους [cite:&fernandez-bolanosCharacterizationLigninObtained1999] ενώ η θερμοχωρητικότητα από την βάση δεδομένων του NREL ως \( 0.25660 + 3.22 \cdot 10^{-3} T \). H πυκνότητα υποτέθηκε και εδώ ίση με του αμύλου.

Αν ορίσουμε τα συστατικά αυτά ως εξής και βάλουμε τα yields όπως έχουν υπολογιστεί στο mass_balances.ods προκύπτει μία προσομοίωση η οποία μπορεί να τρέξει χωρίς error και δίνει σωστά αποτελέσματα.
